(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},w="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");
},ca=ba(this),y=function(a,b){if(b)a:{var c=ca;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&w(c,a,{configurable:!0,writable:!0,value:b})}};
y("Symbol",function(a){if(a)return a;var b=function(e,f){this.Z=e;w(this,"description",{configurable:!0,writable:!0,value:f})};b.prototype.toString=function(){return this.Z};var c=0,d=function(e){if(this instanceof d)throw new TypeError("Symbol is not a constructor");return new b("jscomp_symbol_"+(e||"")+"_"+c++,e)};return d});
y("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=ca[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&w(d.prototype,a,{configurable:!0,writable:!0,value:function(){return da(aa(this))}})}return a});
var da=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a},z=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}},ea=function(a){if(!(a instanceof Array)){a=z(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a},ja="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},ka;
if("function"==typeof Object.setPrototypeOf)ka=Object.setPrototypeOf;else{var la;a:{var ma={a:!0},na={};try{na.__proto__=ma;la=na.a;break a}catch(a){}la=!1}ka=la?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var oa=ka,A=function(a,b){a.prototype=ja(b.prototype);a.prototype.constructor=a;if(oa)oa(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.ia=b.prototype},D=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
y("WeakMap",function(a){function b(){}function c(m){var q=typeof m;return"object"===q&&null!==m||"function"===q}function d(m){if(!D(m,f)){var q=new b;w(m,f,{value:q})}}function e(m){var q=Object[m];q&&(Object[m]=function(u){if(u instanceof b)return u;Object.isExtensible(u)&&d(u);return q(u)})}if(function(){if(!a||!Object.seal)return!1;try{var m=Object.seal({}),q=Object.seal({}),u=new a([[m,2],[q,3]]);if(2!=u.get(m)||3!=u.get(q))return!1;u.delete(m);u.set(q,4);return!u.has(m)&&4==u.get(q)}catch(E){return!1}}())return a;
var f="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var h=0,g=function(m){this.M=(h+=Math.random()+1).toString();if(m){m=z(m);for(var q;!(q=m.next()).done;)q=q.value,this.set(q[0],q[1])}};g.prototype.set=function(m,q){if(!c(m))throw Error("Invalid WeakMap key");d(m);if(!D(m,f))throw Error("WeakMap key fail: "+m);m[f][this.M]=q;return this};g.prototype.get=function(m){return c(m)&&D(m,f)?m[f][this.M]:void 0};g.prototype.has=function(m){return c(m)&&D(m,f)&&D(m[f],this.M)};
g.prototype.delete=function(m){return c(m)&&D(m,f)&&D(m[f],this.M)?delete m[f][this.M]:!1};return g});
y("Map",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var g=Object.seal({x:4}),m=new a(z([[g,"s"]]));if("s"!=m.get(g)||1!=m.size||m.get({x:4})||m.set({x:4},"t")!=m||2!=m.size)return!1;var q=m.entries(),u=q.next();if(u.done||u.value[0]!=g||"s"!=u.value[1])return!1;u=q.next();return u.done||4!=u.value[0].x||"t"!=u.value[1]||!q.next().done?!1:!0}catch(E){return!1}}())return a;var b=new WeakMap,c=function(g){this.L={};this.B=f();
this.size=0;if(g){g=z(g);for(var m;!(m=g.next()).done;)m=m.value,this.set(m[0],m[1])}};c.prototype.set=function(g,m){g=0===g?0:g;var q=d(this,g);q.list||(q.list=this.L[q.id]=[]);q.m?q.m.value=m:(q.m={next:this.B,G:this.B.G,head:this.B,key:g,value:m},q.list.push(q.m),this.B.G.next=q.m,this.B.G=q.m,this.size++);return this};c.prototype.delete=function(g){g=d(this,g);return g.m&&g.list?(g.list.splice(g.index,1),g.list.length||delete this.L[g.id],g.m.G.next=g.m.next,g.m.next.G=g.m.G,g.m.head=null,this.size--,
!0):!1};c.prototype.clear=function(){this.L={};this.B=this.B.G=f();this.size=0};c.prototype.has=function(g){return!!d(this,g).m};c.prototype.get=function(g){return(g=d(this,g).m)&&g.value};c.prototype.entries=function(){return e(this,function(g){return[g.key,g.value]})};c.prototype.keys=function(){return e(this,function(g){return g.key})};c.prototype.values=function(){return e(this,function(g){return g.value})};c.prototype.forEach=function(g,m){for(var q=this.entries(),u;!(u=q.next()).done;)u=u.value,
g.call(m,u[1],u[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(g,m){var q=m&&typeof m;"object"==q||"function"==q?b.has(m)?q=b.get(m):(q=""+ ++h,b.set(m,q)):q="p_"+m;var u=g.L[q];if(u&&D(g.L,q))for(g=0;g<u.length;g++){var E=u[g];if(m!==m&&E.key!==E.key||m===E.key)return{id:q,list:u,index:g,m:E}}return{id:q,list:u,index:-1,m:void 0}},e=function(g,m){var q=g.B;return da(function(){if(q){for(;q.head!=g.B;)q=q.G;for(;q.next!=q.head;)return q=q.next,{done:!1,value:m(q)};q=null}return{done:!0,
value:void 0}})},f=function(){var g={};return g.G=g.next=g.head=g},h=0;return c});
y("Set",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),d=new a(z([c]));if(!d.has(c)||1!=d.size||d.add(c)!=d||1!=d.size||d.add({x:4})!=d||2!=d.size)return!1;var e=d.entries(),f=e.next();if(f.done||f.value[0]!=c||f.value[1]!=c)return!1;f=e.next();return f.done||f.value[0]==c||4!=f.value[0].x||f.value[1]!=f.value[0]?!1:e.next().done}catch(h){return!1}}())return a;var b=function(c){this.v=new Map;if(c){c=
z(c);for(var d;!(d=c.next()).done;)this.add(d.value)}this.size=this.v.size};b.prototype.add=function(c){c=0===c?0:c;this.v.set(c,c);this.size=this.v.size;return this};b.prototype.delete=function(c){c=this.v.delete(c);this.size=this.v.size;return c};b.prototype.clear=function(){this.v.clear();this.size=0};b.prototype.has=function(c){return this.v.has(c)};b.prototype.entries=function(){return this.v.entries()};b.prototype.values=function(){return this.v.values()};b.prototype.keys=b.prototype.values;
b.prototype[Symbol.iterator]=b.prototype.values;b.prototype.forEach=function(c,d){var e=this;this.v.forEach(function(f){return c.call(d,f,f,e)})};return b});y("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});y("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});
var pa=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};y("String.prototype.includes",function(a){return a?a:function(b,c){return-1!==pa(this,b,"includes").indexOf(b,c||0)}});
y("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(g){return g};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof f){b=f.call(b);for(var h=0;!(f=b.next()).done;)e.push(c.call(d,f.value,h++))}else for(f=b.length,h=0;h<f;h++)e.push(c.call(d,b[h],h));return e}});y("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)D(b,d)&&c.push([d,b[d]]);return c}});
y("String.prototype.startsWith",function(a){return a?a:function(b,c){var d=pa(this,b,"startsWith");b+="";var e=d.length,f=b.length;c=Math.max(0,Math.min(c|0,d.length));for(var h=0;h<f&&c<e;)if(d[c++]!=b[h++])return!1;return h>=f}});y("String.prototype.endsWith",function(a){return a?a:function(b,c){var d=pa(this,b,"endsWith");b+="";void 0===c&&(c=d.length);c=Math.max(0,Math.min(c|0,d.length));for(var e=b.length;0<e&&0<c;)if(d[--c]!=b[--e])return!1;return 0>=e}});
var qa=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};y("Array.prototype.values",function(a){return a?a:function(){return qa(this,function(b,c){return c})}});
y("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,f=0;f<e;f++){var h=d[f];if(b.call(c,h,f,d)){b=h;break a}}b=void 0}return b}});y("Array.prototype.flatMap",function(a){return a?a:function(b,c){for(var d=[],e=0;e<this.length;e++){var f=b.call(c,this[e],e,this);Array.isArray(f)?d.push.apply(d,f):d.push(f)}return d}});function ra(){return{g:{Y:[],J:new Set,K:new Set}}};/*

 Copyright 2020 Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
function sa(a,b){var c,d,e,f;return null!==(f=null!==(d=null===(c=a.matches)||void 0===c?void 0:c.call(a,b))&&void 0!==d?d:null===(e=a.msMatchesSelector)||void 0===e?void 0:e.call(a,b))&&void 0!==f?f:a.webkitMatchesSelector(b)}function F(a,b){if(a.closest)return a.closest(b);for(;!sa(a,b);){if(null===a.parentElement)return null;a=a.parentElement}return a};function ta(a){return(H(a,"a")||H(a,"area")||H(a,"link"))&&a.hasAttribute("href")||(H(a,"input")||H(a,"select")||H(a,"textarea")||H(a,"button"))&&!a.hasAttribute("disabled")?!0:a.hasAttribute("tabindex")||a.isContentEditable}function I(a){return a.nodeType===Node.ELEMENT_NODE&&"http://www.w3.org/1999/xhtml"===a.namespaceURI}function ua(a){return a.nodeType===Node.ELEMENT_NODE&&"http://www.w3.org/2000/svg"===a.namespaceURI}function H(a,b){return a.tagName.toLowerCase()===b};function va(a,b){if(!I(a)||H(a,"option")&&null!==F(a,"select")&&b.g.D)return!1;b=window.getComputedStyle(a);if(0===wa(b.height)&&0===wa(b.width)&&!ta(a)||"hidden"===b.visibility||null!==F(a,'[hidden],[aria-hidden="true"]'))return!0;for(;null!==a;){if("none"===window.getComputedStyle(a).display)return!0;a=a.parentElement}return!1}function wa(a){return Number(a.replace("px","").replace("em","").replace("%",""))};function ya(a){var b,c,d=null!==(c=null===(b=a.getAttribute("aria-labelledby"))||void 0===b?void 0:b.split(" "))&&void 0!==c?c:[];a=[];d=z(d);for(var e=d.next();!e.done;e=d.next())(e=document.getElementById(e.value))&&a.push(e);return a};var za=["email","tel","text","url","search"],Aa=["number","range"],Ba=["spinbutton","slider","progressbar","scrollbar"];
function Ca(a){var b,c=null!==(b=a.getAttribute("role"))&&void 0!==b?b:"",d=Ba.includes(c);if(c&&!d)return null;c=H(a,"input")&&Aa.includes(a.type)||H(a,"progress");if(d||c){if(a.hasAttribute("aria-valuetext"))return a.getAttribute("aria-valuetext");if(a.hasAttribute("aria-valuenow"))return a.getAttribute("aria-valuenow");if(H(a,"input"))return a.value;if(H(a,"progress"))return a.value.toString()}return null}
function Da(a,b,c){var d=a.getAttribute("role");if(d&&"listbox"!==d&&"combobox"!==d)return null;if(H(a,"input")&&za.includes(a.type)&&(a.hasAttribute("list")||"combobox"===d))return a.value;var e=[];d&&"listbox"===d?e=Array.from(a.querySelectorAll('[role="option"][aria-selected="true"]')):H(a,"select")&&(e=Array.from(a.selectedOptions));return 0<e.length?e.map(function(f){return c(f,{g:b.g}).name}).filter(function(f){return""!==f}).join(" "):null}
function Ea(a,b,c){if(!I(a)||!b.g.D)return null;var d;return(d=(d=a.getAttribute("role"))&&"textbox"!==d?null:H(a,"textarea")||H(a,"input")&&za.includes(a.type)&&!a.hasAttribute("list")?a.value:null)?d:(b=Da(a,b,c))?b:(a=Ca(a))?a:null};var Fa="BUTTON INPUT METER OUTPUT PROGRESS SELECT TEXTAREA".split(" ");function Ga(a,b,c){return Array.from(document.querySelectorAll("label")).filter(function(d){return void 0!==d.control?d.control===a:""!==d.htmlFor&&d.htmlFor===a.id?!0:""===d.htmlFor&&d.contains(a)?!0:!1}).map(function(d){return c(d,{P:!0,g:b.g}).name}).filter(function(d){return""!==d}).join(" ")||null};var Ha={U:"button cell checkbox columnheader gridcell heading link menuitem menuitemcheckbox menuitemradio option radio row rowgroup rowheader switch tab tooltip tree treeitem".split(" "),tags:"button h1 h2 h3 h4 h5 h6 summary tbody tfoot thead".split(" ")},Ia={U:"alert alertdialog application article banner complementary dialog document feed figure form grid group img listbox log main marquee math menu menubar navigation radiogroup region scrollbar search searchbox separator slider spinbutton tablist tabpanel textbox timer toolbar treegrid".split(" "),
tags:"article aside body datalist dialog fieldset figure footer form header hr img input main math menu nav optgroup section select textarea".split(" ")},Ja={U:"contentinfo definition directory list note status table term".split(" "),tags:"dd details dl ol output table ul".split(" ")};
function Ka(a){switch(a){case "th":return function(b){return null!==F(b,"table")};case "td":return function(b){return null!==F(b,"table")};case "option":return function(b){return null!==F(b,"select,datalist")};case "a":return function(b){return b.hasAttribute("href")};case "area":return function(b){return b.hasAttribute("href")};case "link":return function(b){return b.hasAttribute("href")};default:return null}}
function J(a,b){var c,d,e=null!==(d=null===(c=a.getAttribute("role"))||void 0===c?void 0:c.trim().toLowerCase())&&void 0!==d?d:"";return b.U.includes(e)||b.tags.includes(a.nodeName.toLowerCase())?!0:!1}function La(a,b){var c;if(b.g.D&&a.parentElement&&J(a.parentElement,Ha)&&J(a,Ja))return!0;if(J(a,Ia))return"menu"===(null===(c=a.getAttribute("role"))||void 0===c?void 0:c.toLowerCase())?!1:ta(a);if(J(a,Ha))return!0;var d=Ka(a.nodeName.toLowerCase());return d&&d(a)||b.P||b.g.D?!0:!1}
function Ma(a,b){b=window.getComputedStyle(a,b);a=b.content;b="block"===b.display;return'"'===a[0]&&'"'===a[a.length-1]||"'"===a[0]&&"'"===a[a.length-1]?b?" "+a.slice(1,-1)+" ":a.slice(1,-1):""}var Na="a abbr acronym b bdi bdo big button canvas cite code data datalist del dfn em embed i iframe img ins kbd label map mark meter noscript object output picture progress q ruby s samp script select slot small span strong sub sup template textarea time tt u var video wbr".split(" ");var Oa="text password search tel email url".split(" ");var Pa={"2A":function(a,b){var c=null;va(a,b)&&!b.P&&(c="");return c},"2B":function(a,b,c){if(!I(a)||b.P)return null;a=ya(a);return 0===a.length?null:a.map(function(d){b.g.D=!0;return c(d,{P:!0,g:b.g}).name}).join(" ").trim()},"2C":function(a,b,c){var d;if(!I(a))return null;var e=null!==(d=a.getAttribute("aria-label"))&&void 0!==d?d:"";return""===e.trim()?null:b.g.D&&(a=Ea(a,{g:b.g},c),null!==a)?a:e},"2D":function(a,b,c){var d;if(ua(a))for(var e=z(a.childNodes),f=e.next();!f.done;f=e.next())if(f=
f.value,ua(f)&&H(f,"title"))return f.textContent;if(!I(a))return null;e=null!==(d=a.getAttribute("role"))&&void 0!==d?d:"";if("presentation"===e||"none"===e)return null;if(Fa.includes(a.tagName)&&(e=Ga(a,b,c)))return e;if(H(a,"input")){var h;e=null!==(h=a.getAttribute("type"))&&void 0!==h?h:"";if(h="button"!==e&&"submit"!==e&&"reset"!==e||!a.hasAttribute("value")?"submit"===e||"reset"===e?e:"image"===e&&a.hasAttribute("alt")?a.getAttribute("alt"):"image"!==e||a.hasAttribute("title")?null:"Submit Query":
a.value)return h}return H(a,"table")&&(h=a.querySelector("caption"))?(b.g.D=!0,c(h,{g:b.g}).name):H(a,"figure")&&(h=a.querySelector("figcaption"))?(b.g.D=!0,c(h,{g:b.g}).name):H(a,"fieldset")&&(h=a.querySelector("legend"))?(b.g.D=!0,c(h,{g:b.g}).name):(b=a.getAttribute("alt"))&&(H(a,"img")||H(a,"area"))?b:null},"2E":Ea,"2F":function(a,b,c){if(!I(a)||!La(a,b))return null;var d=Array.from(a.childNodes),e=a.getAttribute("aria-owns");if(e){e=z(e.split(" "));for(var f=e.next();!f.done;f=e.next())(f=document.getElementById(f.value))&&
d.push(f)}e=[];d=z(d);for(f=d.next();!f.done;f=d.next())if(f=f.value,!b.g.Y.includes(f)){b.g.Y.push(f);b.g.D=!0;var h=c(f,{g:b.g}).name;Na.includes(f.nodeName.toLowerCase())||f.nodeType===Node.TEXT_NODE?e.push(h):e.push(" "+h+" ")}e.unshift(Ma(a,":before"));e.push(Ma(a,":after"));a=e.join("");return""===a.trim()?null:a},"2G":function(a){return a.nodeType===Node.TEXT_NODE?a.data:null},"2I":function(a){return I(a)?a.title?a.title:H(a,"input")&&Oa.includes(a.type)?a.placeholder:H(a,"textarea")&&a.hasAttribute("placeholder")?
a.getAttribute("placeholder"):null:null}};function Qa(a){var b=void 0===b?ra():b;a=Ra(a,b);return{name:a.name.trim(),J:a.J,K:a.K}}function Ra(a,b){b=void 0===b?ra():b;b.g.J.add(a);for(var c=z(Object.entries(Pa)),d=c.next();!d.done;d=c.next()){var e=z(d.value);d=e.next().value;e=e.next().value;e=e(a,b,Ra);if(null!==e)return b.g.K.add(d),{name:e.replace(/\s+/g," "),J:b.g.J,K:b.g.K}}return{name:"",J:b.g.J,K:b.g.K}};/*

 Copyright 2021 Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
var K=function(){var a=Error.apply(this,arguments);this.message=a.message;"stack"in a&&(this.stack=a.stack);this.R="SemanticLocatorError"};A(K,Error);var Sa=function(){K.apply(this,arguments);this.R="NoSuchElementError"};A(Sa,K);var Ta=function(){K.apply(this,arguments);this.R="ValueError"};A(Ta,K);var L=function(){K.apply(this,arguments);this.R="InvalidLocatorError"};A(L,K);function Ua(a){return Qa(a).name};var Va="checked current disabled selected colindex level posinset readonly rowindex".split(" ");var Wa=new Set("alert alertdialog application directory feed grid log marquee menu menubar menuitem menuitemcheckbox menuitemradio note radiogroup scrollbar search switch tab tablist tabpanel timer toolbar tooltip tree treegrid treeitem".split(" ")),Xa="button checkbox img math menuitemcheckbox menuitemradio progressbar radio scrollbar separator slider switch tab".split(" "),M={article:{h:"article"},banner:{l:[{j:"header",conditions:[{type:1,W:'article,aside,main,nav,section,[role="article"],[role="complementary"],[role="main"],[role="navigation"],[role="region"]'}]}]},
button:{h:"button,summary",l:[{j:"input",conditions:[{type:5,propertyName:"type",values:["button","image","reset","submit"]}]}]},cell:{l:[{j:"td",conditions:[{type:6,tag:"table",i:"table"}]},{j:'th:not([scope="col"]):not([scope="colgroup"]):not([scope="row"]):not([scope="rowgroup"])',conditions:[{type:6,tag:"table",i:"table"},{type:8,T:!0},{type:7,O:!0}]}]},checkbox:{l:[{j:"input",conditions:[{type:5,propertyName:"type",values:["checkbox"]}]}]},columnheader:{h:'th[scope="col"],th[scope="colgroup"]',
l:[{j:'th:not([scope="col"]):not([scope="colgroup"]):not([scope="row"]):not([scope="rowgroup"])',conditions:[{type:7,O:!1}]}]},combobox:{h:"select:not([multiple]):not([size])",l:[{j:"select:not([multiple])",conditions:[{type:3,s:"size",value:2}]},{j:"input[list]",conditions:[{type:5,propertyName:"type",values:["email","search","tel","text","url"]}]}]},complementary:{h:"aside"},contentinfo:{l:[{j:"footer",conditions:[{type:1,W:'article,aside,main,nav,section,[role="article"],[role="complementary"],[role="main"],[role="navigation"],[role="region"]'}]}]},
definition:{h:"dd"},dialog:{h:"dialog"},document:{h:"body"},figure:{h:"figure"},form:{l:[{j:"form",conditions:[{type:4}]}]},gridcell:{l:[{j:"td",conditions:[{type:6,tag:"table",i:"grid"}]},{j:"td",conditions:[{type:6,tag:"table",i:"treegrid"}]},{j:'th:not([scope="col"]):not([scope="colgroup"]):not([scope="row"]):not([scope="rowgroup"])',conditions:[{type:6,tag:"table",i:"treegrid"},{type:8,T:!0},{type:7,O:!0}]}]},group:{h:"details,fieldset,optgroup"},heading:{h:"h1,h2,h3,h4,h5,h6"},img:{h:'img:not([alt]),img[alt]:not([alt=""])'},
link:{h:"a[href],area[href],link[href]"},list:{h:"menu,ol,ul"},listbox:{h:"datalist,select[multiple]",l:[{j:"select",conditions:[{type:2,s:"size",value:1}]}]},listitem:{h:"li"},main:{h:"main"},math:{h:"math"},navigation:{h:"nav"},option:{h:"datalist > option,select > optgroup > option,select > option"},progressbar:{h:"progress"},radio:{l:[{j:"input",conditions:[{type:5,propertyName:"type",values:["radio"]}]}]},region:{l:[{j:"section",conditions:[{type:4}]}]},row:{h:"tr"},rowgroup:{h:"tbody,tfoot,thead"},
rowheader:{h:'th[scope="row"],th[scope="rowgroup"]',l:[{j:'th:not([scope="col"]):not([scope="colgroup"]):not([scope="row"]):not([scope="rowgroup"])',conditions:[{type:8,T:!1},{type:7,O:!0}]}]},searchbox:{l:[{j:"input:not([list])",conditions:[{type:5,propertyName:"type",values:["search"]}]}]},separator:{h:"hr"},slider:{l:[{j:"input",conditions:[{type:5,propertyName:"type",values:["range"]}]}]},spinbutton:{l:[{j:"input",conditions:[{type:5,propertyName:"type",values:["number"]}]}]},status:{h:"output"},
table:{h:"table"},term:{h:"dfn,dt"},textbox:{h:"textarea",l:[{j:"input:not([list])",conditions:[{type:5,propertyName:"type",values:["email","tel","text","url"]}]}]}},Ya={a:["link"],area:["link"],article:["article"],aside:["complementary"],body:["document"],button:["button"],datalist:["listbox"],dd:["definition"],details:["group"],dfn:["term"],dialog:["dialog"],dt:["term"],fieldset:["group"],figure:["figure"],footer:["contentinfo"],form:["form"],h1:["heading"],h2:["heading"],h3:["heading"],h4:["heading"],
h5:["heading"],h6:["heading"],header:["banner"],hr:["separator"],img:["img"],input:"button checkbox combobox radio searchbox slider spinbutton textbox".split(" "),li:["listitem"],link:["link"],main:["main"],math:["math"],menu:["list"],nav:["navigation"],ol:["list"],optgroup:["group"],option:["option"],output:["status"],progress:["progressbar"],section:["region"],select:["combobox","listbox"],summary:["button"],table:["table"],tbody:["rowgroup"],td:["cell","gridcell"],textarea:["textbox"],tfoot:["rowgroup"],
th:["cell","columnheader","gridcell","rowheader"],thead:["rowgroup"],tr:["row"],ul:["list"]},Za=["none","presentation"];function $a(a){throw Error("unexpected value "+a+"!");}function ab(a){if(bb())for(var b=1;b<a.length;b++)if(0<N(a[b-1],a[b]))throw Error("Elements not passed in document order. Index "+(b-1)+" comes after index "+(b+". Elements: "+JSON.stringify(a)));}function N(a,b){return a===b?0:a.compareDocumentPosition(b)&Node.DOCUMENT_POSITION_PRECEDING?1:-1}function cb(a){return a.filter(function(b,c){return a[c-1]!==b})}function O(a,b){return a.tagName.toLowerCase()===b}
function P(a,b){if(bb()&&!a)throw a="Assertion failed",void 0!==b&&(a+=": "+b),Error(a);}function bb(){var a,b;return(null===(b=null===(a=window)||void 0===a?void 0:a.ha)||void 0===b?void 0:b.fa)||!1};function db(a,b){a=eb(a);b=fb(a,b);return a.cells.slice(b.da,b.ba+1).some(function(c){return c.some(Q)})}function qb(a,b){a=eb(a);b=fb(a,b);var c=b.ca,d=b.aa;return a.cells.some(function(e){return e.slice(c,d+1).some(Q)})}
var R=function(a){this.cells=a=void 0===a?[]:a},rb=function(a,b,c){return S(a,c)[b]},S=function(a,b){void 0===a.cells[b]&&(a.cells[b]=[]);return a.cells[b]},fb=function(a,b){for(var c=a.width,d=a.height,e=-1,f=-1,h=0;h<a.height;h++){var g=S(a,h),m=g.indexOf(b);-1!==m&&(e=Math.max(e,g.lastIndexOf(b)),f=Math.max(f,h),c=Math.min(c,m),d=Math.min(d,h))}P(e<a.width&&f<a.height&&-1<c&&-1<d,"Target cell not found in table");return{ca:c,da:d,aa:e,ba:f}};R.prototype.concat=function(a){this.cells=this.cells.concat(a.cells)};
ca.Object.defineProperties(R.prototype,{height:{configurable:!0,enumerable:!0,get:function(){return this.cells.length}},width:{configurable:!0,enumerable:!0,get:function(){return Math.max.apply(Math,ea(this.cells.map(function(a){return a.length})))}}});
function eb(a){var b=new R;null!==a.tHead&&b.concat(sb(a.tHead.rows));for(var c=z(a.tBodies),d=c.next();!d.done;d=c.next())b.concat(sb(d.value.rows));c=[];d=z(a.children);for(var e=d.next();!e.done;e=d.next())e=e.value,e.nodeType===Node.ELEMENT_NODE&&"http://www.w3.org/1999/xhtml"===e.namespaceURI&&O(e,"tr")&&c.push(e);b.concat(sb(c));null!==a.tFoot&&b.concat(sb(a.tFoot.rows));return b}
function sb(a){for(var b=new R,c=[],d=0;d<a.length;d++){for(var e=0,f=z(a[d].cells),h=f.next();!h.done;h=f.next()){for(h=h.value;rb(b,e,d)||c[e];){if(!Q(rb(b,e,d))&&c[e]){var g=e,m=c[e];S(b,d)[g]=m}e++}for(g=e;g<e+h.colSpan;g++)for(0===tb(h)&&(c[g]=h,m=g,S(b,d)[m]=h),m=d;m<d+tb(h);m++)if(!Q(rb(b,g,m))){var q=g;S(b,m)[q]=h}e+=h.colSpan}for(;e<b.width;e++)f=c[e],void 0===f||Q(rb(b,e,d))||(h=e,S(b,d)[h]=f)}return b}
function tb(a){a=a.getAttribute("rowSpan");if(null===a||""===a.trim())return 1;a=Number(a);return isNaN(a)?1:a}function Q(a){return void 0!==a&&O(a,"td")};function ub(a,b,c,d){var e,f=Array.from(b.querySelectorAll('[role="'+a+'"]'));if(Wa.has(a))return f.filter(function(m){return c||!vb(m)}).filter(function(m){return d||!wb(m)});f=new Set(f);a=M[a];var h=a.h;if(h){h=xb(h,b);var g=z(h);for(h=g.next();!h.done;h=g.next())f.add(h.value)}a=z(null!==(e=a.l)&&void 0!==e?e:[]);for(h=a.next();!h.done;h=a.next())for(h=h.value,h=xb(h.j,b,h.conditions),g=z(h),h=g.next();!h.done;h=g.next())f.add(h.value);return Array.from(f).filter(function(m){return c||!vb(m)}).filter(function(m){return d||
!wb(m)}).sort(N)}function yb(a){var b,c=a.getAttribute("role");if(c){if(Za.includes(c))return null;if(Wa.has(c)||M.hasOwnProperty(c))return c}return(null!==(b=Ya[a.tagName.toLowerCase()])&&void 0!==b?b:[]).find(function(d){return zb(a,d)})||null}function vb(a){if("hidden"===window.getComputedStyle(a).visibility||null!==T(a,'[aria-hidden="true"]'))return!0;for(;null!==a;){if("none"===window.getComputedStyle(a).display)return!0;a=a.parentElement}return!1}
function Ab(a,b){switch(b.type){case 2:var c=a.getAttribute(b.s);return null!==c&&Number(c)>b.value;case 3:return c=a.getAttribute(b.s),null!==c&&Number(c)<b.value;case 4:return a.hasAttribute("aria-label")||a.hasAttribute("aria-labelledby")&&a.getAttribute("aria-labelledby").split(" ").some(function(d){return void 0!==document.getElementById(d)});case 1:return null===T(a,b.W);case 0:return a[b.propertyName]===b.value;case 5:return b.values.some(function(d){return d===a[b.propertyName]});case 6:c=
a.parentElement;if(null===c)return!1;c=T(c,b.tag);return null!==c&&yb(c)===b.i;case 8:return c=T(a,"table"),null===c?!1:b.T===qb(c,a);case 7:return c=T(a,"table"),null===c?!1:b.O===db(c,a);default:$a(b)}}function Bb(a,b,c){var d=Cb(a.parentElement,b);return null===d?null:c.flatMap(function(e){return ub(e,d,!1,!1)}).filter(function(e){return d===Cb(e.parentElement,b)}).sort(N).indexOf(a)+1||null}
function zb(a,b){var c,d;b=M[b];var e=b.h;return e&&Db(a,e)?!0:null!==(d=null===(c=b.l)||void 0===c?void 0:c.some(function(f){return Db(a,f.j)&&f.conditions.every(function(h){return Ab(a,h)})}))&&void 0!==d?d:!1}function wb(a){for(var b=z(Xa),c=b.next();!c.done;c=b.next())if(null!==Cb(a.parentElement,c.value))return!0;return!1}
function Cb(a,b){var c,d='[role="'+b+'"]';if(M.hasOwnProperty(b)){var e=M[b];void 0!==e.h&&(d+=","+Eb(e.h));for(var f=z(null!==(c=e.l)&&void 0!==c?c:[]),h=f.next();!h.done;h=f.next())if("input"!==h.value.j)throw Error("Not implemented: closestWithRole called with a role which requires a condition to be checked. Role: "+b+"; Selector: "+e);}return T(a,d)}function xb(a,b,c){a=Array.from(b.querySelectorAll(Eb(a)));return c?a.filter(function(d){return c.every(function(e){return Ab(d,e)})}):a}
function Eb(a){return a.split(",").map(function(b){return b+":not([role])"}).join(",")}function Db(a,b){var c,d,e,f;return null!==(f=null!==(d=null===(c=a.matches)||void 0===c?void 0:c.call(a,b))&&void 0!==d?d:null===(e=a.msMatchesSelector)||void 0===e?void 0:e.call(a,b))&&void 0!==f?f:a.webkitMatchesSelector(b)}function T(a,b){if(a.closest)return a.closest(b);for(;!Db(a,b);){if(null===a.parentElement)return null;a=a.parentElement}return a};function Fb(a,b){if(a.hasAttribute("aria-"+b))return a.getAttribute("aria-"+b);switch(b){case "checked":return O(a,"input")&&["checkbox","radio"].includes(a.type)?a.checked.toString():null;case "current":return"false";case "disabled":return((O(a,"button")||O(a,"fieldset")||O(a,"input")||O(a,"optgroup")||O(a,"option")||O(a,"select")||O(a,"textarea"))&&a.disabled).toString();case "selected":return O(a,"option")?a.selected.toString():null;case "colindex":return(a=Bb(a,"row",["columnheader","cell"]))?
String(a):null;case "level":return a=a.tagName.match(/^H([1-6])$/),null===a?null:a[1];case "rowindex":return(a=Bb(a,"table",["row"]))?String(a):null;case "posinset":return b=yb(a),"listitem"===b?(a=Bb(a,"list",["listitem"]))?String(a):null:"treeitem"===b?(a=Bb(a,"tree",["treeitem"]))?String(a):null:null;case "readonly":return(O(a,"input")&&a.readOnly||"false"===a.contentEditable).toString();default:$a(b)}};function U(a){return void 0!==a.u}function Gb(a){return void 0!==a.o}function W(a){return void 0!==a.i?"an ARIA role of "+a.i:void 0!==a.s?"aria-"+a.s.name+" = "+a.s.value:'an accessible name of "'+a.name+'"'}function Hb(a){var b,c=[];a.i&&c.push(W({i:a.i}));a.attributes&&(c=c.concat(a.attributes.map(function(d){return W({s:d})})));a.name&&c.push(W({name:a.name}));return 1>=c.length?null!==(b=c[0])&&void 0!==b?b:"":c.slice(0,c.length-1).join(", ")+(", and "+c[c.length-1])}
function Ib(a,b){if(void 0!==a.i)return b=b.map(function(c){return yb(c)}).filter(function(c){return null!=c}),"Roles found: "+JSON.stringify(Array.from(new Set(b)));if(void 0!==a.s)return b=b.map(function(c){return Fb(c,a.s.name)}),"Values found for aria-"+a.s.name+": "+JSON.stringify(Array.from(new Set(b)));b=b.map(Ua).filter(function(c){return""!==c});return 0===b.length?"No matching elements had an accessible name":"Accessible names found: "+JSON.stringify(Array.from(new Set(b)))}
function Jb(a){var b=a.map(Kb),c=Math.max.apply(Math,ea(b));a=a.filter(function(d,e){return b[e]===c});return{u:cb(a.flatMap(function(d){return d.u}).sort(N)),A:a[0].A,F:a[0].F,C:a[0].C}}function Kb(a){var b,c=a.A.length;a=null!==(b=a.F)&&void 0!==b?b:{};var d=0;void 0!==a.i&&d++;void 0!==a.attributes&&(d+=a.attributes.length);void 0!==a.name&&d++;return c+d/50};function Lb(a){ab(a);if(0===a.length)return[];var b=[a[0]];a=z(a);for(var c=a.next();!c.done;c=a.next())c=c.value,b[b.length-1].contains(c)||b.push(c);return b};var X=function(a,b){this.S=a;this.N=b;a=a.concat(b);b=z(a);for(var c=b.next();!c.done;c=b.next()){c=c.value;var d=c.i;if(!Wa.has(d)&&!M.hasOwnProperty(d))throw new L("Invalid locator: "+this+(" Unknown role: "+c.i+". The list of valid roles can be found at https://www.w3.org/TR/wai-aria/#role_definitions"));if(c!==a[a.length-1]&&Xa.includes(c.i))throw new L("Invalid locator: "+this+(' The role "'+c.i+'" has presentational children. That means its descendants cannot have semantics, so an element with a role of ')+
(c.i+" may only be the final element of a Semantic Locator. https://www.w3.org/TR/wai-aria-practices/#children_presentational"));c=z(c.attributes);for(d=c.next();!d.done;d=c.next())if(d=d.value,!Va.includes(d.name))throw new L("Invalid locator: "+this+(" Unsupported attribute: "+d.name+". Supported attributes: ")+Va);}};
X.prototype.toString=function(){for(var a=[],b=z(this.S),c=b.next();!c.done;c=b.next())a.push(c.value.toString());if(0<this.N.length)for(a.push("outer"),b=z(this.N),c=b.next();!c.done;c=b.next())a.push(c.value.toString());return a.join(" ")};var Mb=function(a,b,c){this.i=a;this.attributes=b;this.name=c};
Mb.prototype.toString=function(){var a="{"+this.i;if(this.name){a+=" ";var b=this.name;b=b.includes("'")&&!b.includes('"')?JSON.stringify(b):"'"+b.replace(/'/g,"\\'")+"'";a+=b}b=z(this.attributes);for(var c=b.next();!c.done;c=b.next())c=c.value,a+=" "+c.name+":"+c.value;return a+"}"};var Nb=function(a,b,c,d){b=Error.call(this);this.message=b.message;"stack"in b&&(this.stack=b.stack);this.message=a;this.o=c;this.location=d;this.name="SyntaxError";"function"===typeof Error.captureStackTrace&&Error.captureStackTrace(this,Nb)};A(Nb,Error);
var Ob=function(a,b){function c(h){return h.charCodeAt(0).toString(16).toUpperCase()}function d(h){return h.replace(/\\/g,"\\\\").replace(/"/g,'\\"').replace(/\0/g,"\\0").replace(/\t/g,"\\t").replace(/\n/g,"\\n").replace(/\r/g,"\\r").replace(/[\x00-\x0F]/g,function(g){return"\\x0"+c(g)}).replace(/[\x10-\x1F\x7F-\x9F]/g,function(g){return"\\x"+c(g)})}function e(h){return h.replace(/\\/g,"\\\\").replace(/\]/g,"\\]").replace(/\^/g,"\\^").replace(/-/g,"\\-").replace(/\0/g,"\\0").replace(/\t/g,"\\t").replace(/\n/g,
"\\n").replace(/\r/g,"\\r").replace(/[\x00-\x0F]/g,function(g){return"\\x0"+c(g)}).replace(/[\x10-\x1F\x7F-\x9F]/g,function(g){return"\\x"+c(g)})}function f(h){switch(h.type){case "literal":return'"'+d(h.text)+'"';case "class":var g=h.ea.map(function(m){return Array.isArray(m)?e(m[0])+"-"+e(m[1]):e(m)});return"["+(h.$?"^":"")+g+"]";case "any":return"any character";case "end":return"end of input";case "other":return h.description}}return"Expected "+function(h){h=h.map(f);var g,m;h.sort();if(0<h.length){for(m=
g=1;g<h.length;g++)h[g-1]!==h[g]&&(h[m]=h[g],m++);h.length=m}switch(h.length){case 1:return h[0];case 2:return h[0]+" or "+h[1];default:return h.slice(0,-1).join(", ")+", or "+h[h.length-1]}}(a)+" but "+(b?'"'+d(b)+'"':"end of input")+" found."};
function Pb(a){function b(l,p){return{type:"literal",text:l,ignoreCase:p}}function c(l,p,r){return{type:"class",ea:l,$:p,ignoreCase:r}}function d(l){var p=fa[l],r;if(!p){for(r=l-1;!fa[r];)r--;p=fa[r];for(p={line:p.line,I:p.I};r<l;)10===a.charCodeAt(r)?(p.line++,p.I=1):p.I++,r++;fa[l]=p}return p}function e(l,p){var r=d(l),t=d(p);return{start:{offset:l,line:r.line,I:r.I},end:{offset:p,line:t.line,I:t.I}}}function f(l){n<B||(n>B&&(B=n,xa=[]),xa.push(l))}function h(){var l;var p=n;var r=[];for(l=g();l!==
k;)r.push(l),l=g();if(r!==k){l=n;if("outer"===a.substr(n,5)){var t="outer";n+=5}else t=k,0===v&&f(Zb);t===k&&(t=null);if(t!==k)if(t=G(),t!==k){t=[];var x=g();if(x!==k)for(;x!==k;)t.push(x),x=g();else t=k;t!==k?l=t:(n=l,l=k)}else n=l,l=k;else n=l,l=k;l===k&&(l=null);l!==k?(p=l||[],p=r=new X(r,p)):(n=p,p=k)}else n=p,p=k;return p}function g(){var l;var p=n;if(123===a.charCodeAt(n)){var r="{";n++}else r=k,0===v&&f($b);if(r!==k)if(r=G(),r!==k)if(r=q(),r!==k){var t=G();if(t!==k){t=n;if(34===a.charCodeAt(n)){var x=
'"';n++}else x=k,0===v&&f(ha);if(x!==k){x=[];for(l=u();l!==k;)x.push(l),l=u();x!==k?(34===a.charCodeAt(n)?(l='"',n++):(l=k,0===v&&f(ha)),l!==k?t=x=x.join(""):(n=t,t=k)):(n=t,t=k)}else n=t,t=k;if(t===k)if(t=n,39===a.charCodeAt(n)?(x="'",n++):(x=k,0===v&&f(ia)),x!==k){x=[];for(l=E();l!==k;)x.push(l),l=E();x!==k?(39===a.charCodeAt(n)?(l="'",n++):(l=k,0===v&&f(ia)),l!==k?t=x=x.join(""):(n=t,t=k)):(n=t,t=k)}else n=t,t=k;t===k&&(t=null);if(t!==k)if(x=G(),x!==k){x=[];for(l=m();l!==k;)x.push(l),l=m();x!==
k?(l=G(),l!==k?(125===a.charCodeAt(n)?(l="}",n++):(l=k,0===v&&f(ac)),l!==k?(l=G(),l!==k?p=r=t?new Mb(r,x,t):new Mb(r,x):(n=p,p=k)):(n=p,p=k)):(n=p,p=k)):(n=p,p=k)}else n=p,p=k;else n=p,p=k}else n=p,p=k}else n=p,p=k;else n=p,p=k;else n=p,p=k;return p}function m(){var l=n;var p=G();if(p!==k)if(p=q(),p!==k){if(58===a.charCodeAt(n)){var r=":";n++}else r=k,0===v&&f(bc);if(r!==k){r=[];if(gb.test(a.charAt(n))){var t=a.charAt(n);n++}else t=k,0===v&&f(hb);if(t!==k)for(;t!==k;)r.push(t),gb.test(a.charAt(n))?
(t=a.charAt(n),n++):(t=k,0===v&&f(hb));else r=k;r!==k&&(r=r.join(""));r!==k?(t=G(),t!==k?l=p={name:p,value:r}:(n=l,l=k)):(n=l,l=k)}else n=l,l=k}else n=l,l=k;else n=l,l=k;return l}function q(){var l=[];if(ib.test(a.charAt(n))){var p=a.charAt(n);n++}else p=k,0===v&&f(jb);if(p!==k)for(;p!==k;)l.push(p),ib.test(a.charAt(n))?(p=a.charAt(n),n++):(p=k,0===v&&f(jb));else l=k;l!==k&&(l=l.join(""));return l}function u(){var l;var p=l=n;v++;if(34===a.charCodeAt(n)){var r='"';n++}else r=k,0===v&&f(ha);r===k&&
(92===a.charCodeAt(n)?(r="\\",n++):(r=k,0===v&&f(V)));v--;r===k?p=void 0:(n=p,p=k);p!==k?(a.length>n?(r=a.charAt(n),n++):(r=k,0===v&&f(kb)),r!==k?l=r:(n=l,l=k)):(n=l,l=k);l===k&&(l=n,92===a.charCodeAt(n)?(p="\\",n++):(p=k,0===v&&f(V)),p!==k?(r=lb(),r!==k?l=r:(n=l,l=k)):(n=l,l=k));return l}function E(){var l;var p=l=n;v++;if(39===a.charCodeAt(n)){var r="'";n++}else r=k,0===v&&f(ia);r===k&&(92===a.charCodeAt(n)?(r="\\",n++):(r=k,0===v&&f(V)));v--;r===k?p=void 0:(n=p,p=k);p!==k?(a.length>n?(r=a.charAt(n),
n++):(r=k,0===v&&f(kb)),r!==k?l=r:(n=l,l=k)):(n=l,l=k);l===k&&(l=n,92===a.charCodeAt(n)?(p="\\",n++):(p=k,0===v&&f(V)),p!==k?(r=lb(),r!==k?l=r:(n=l,l=k)):(n=l,l=k));return l}function lb(){if(39===a.charCodeAt(n)){var l="'";n++}else l=k,0===v&&f(ia);l===k&&(34===a.charCodeAt(n)?(l='"',n++):(l=k,0===v&&f(ha)),l===k&&(92===a.charCodeAt(n)?(l="\\",n++):(l=k,0===v&&f(V))));return l}function G(){v++;var l=[];if(mb.test(a.charAt(n))){var p=a.charAt(n);n++}else p=k,0===v&&f(nb);for(;p!==k;)l.push(p),mb.test(a.charAt(n))?
(p=a.charAt(n),n++):(p=k,0===v&&f(nb));v--;l===k&&0===v&&f(cc);return l}var C=void 0!==C?C:{};var k={},ob={ga:h},pb=h,Zb=b("outer",!1),$b=b("{",!1),ac=b("}",!1),bc=b(":",!1),ib=/^[a-z]/,jb=c([["a","z"]],!1,!1),gb=/^[a-z0-9_]/,hb=c([["a","z"],["0","9"],"_"],!1,!1),ha=b('"',!1),ia=b("'",!1),V=b("\\",!1),kb={type:"any"},cc={type:"other",description:"space"},mb=/^[ \t]/,nb=c([" ","\t"],!1,!1),n=0,fa=[{line:1,I:1}],B=0,xa=[],v=0;if(void 0!==C.V){if(!(C.V in ob))throw Error("Can't start parsing from rule \""+
C.V+'".');pb=ob[C.V]}C=pb();if(C!==k&&n===a.length)return C;C!==k&&n<a.length&&f({type:"end"});throw function(l,p,r){return new Nb(Ob(l,p),l,p,r)}(xa,B<a.length?a.charAt(B):null,B<a.length?e(B,B+1):e(B,B));};function Qb(a){var b;try{var c=Pb(a)}catch(d){if(d instanceof L)throw d;throw new L('Failed to parse semantic locator "'+a+'". '+(null!==(b=d.message)&&void 0!==b?b:d));}if(bb()&&!(c instanceof X))throw Error("parse("+a+") didn't return a SemanticLocator. Return value "+JSON.stringify(c));a=c;if(0===a.S.length&&0===a.N.length)throw new L("Locator is empty");return a};function Y(a,b,c,d){b=void 0===b?document.body:b;c=void 0===c?!1:c;d=void 0===d?!1:d;b=Rb(a.S,[b],c,d);if(U(b)||0===a.N.length)return b;b=b.o.map(function(f){return Rb(a.N,[f],c,d)});var e=b.filter(Gb).flatMap(function(f){return Lb(f.o)});return 0===e.length?(b=Jb(b),{A:a.S.concat(b.A),u:b.u,C:b.C,F:b.F}):{o:cb(e.sort(N))}}function Rb(a,b,c,d){for(var e=0;e<a.length;e++){b=Sb(a[e],b,c,d);if(U(b))return{A:a.slice(0,e),u:b.u,C:b.C,F:b.F};b=b.o}return{o:b}}
function Sb(a,b,c,d){b=Lb(b);var e=b.flatMap(function(g){return ub(a.i,g,c,d)});if(0===e.length)return{A:[],u:b,C:{i:a.i}};var f=a.attributes;for(b={H:0};b.H<f.length;b={H:b.H},b.H++){var h=e.filter(function(g){return function(m){return Fb(m,f[g.H].name)===f[g.H].value}}(b));if(0===h.length)return{A:[],u:e,C:{s:f[b.H]},F:{i:a.i,attributes:f.slice(0,b.H)}};e=h}if(a.name){b=e.filter(function(g){a:{var m=a.name;g=Qa(g).name;if("*"===m)throw new Ta("* is invalid as an accessible name. To match any accessible name omit it from the locator e.g. {button}.");
var q=m.split("*");if(g.startsWith(q[0])&&g.endsWith(q[q.length-1])){m=0;q=z(q);for(var u=q.next();!u.done;u=q.next()){u=u.value;m=g.indexOf(u,m);if(-1===m){g=!1;break a}m+=u.length}g=!0}else g=!1}return g});if(0===b.length)return{A:[],u:e,C:{name:a.name},F:{i:a.i,attributes:a.attributes}};e=b}ab(e);return{o:e}};function Tb(a,b){if(b&&!b.contains(a))throw Error("Can't generate locator for element that is not contained within the root element.");if(!b){a=a.ownerDocument;if(!a)throw Error("Can't generate locator for detached element");b=a.body}return b}
function Ub(a,b){var c;a=Vb(a,b);if(null===a)return null;for(var d=[a.node],e=a.element.parentElement;null!==e;)e=Vb(e,b),null!==e&&(Xa.includes(e.node.i)&&(console.warn("Element "+e.element+" has a role of "+(e.node.i+", so it has presentational children (https://www.w3.org/TR/wai-aria-practices/#children_presentational). However it also has descendant elements which would otherwise have semantics - matched by semantic locator ")+(new X(d,[])+". These presentational elements will be ignored while generating this semantic locator")),
d=[],a=e),d.unshift(e.node)),e=null!==(c=null===e||void 0===e?void 0:e.element.parentElement)&&void 0!==c?c:null;P(Wb(d,b).includes(a.element),"Cannot find element again with locator we just generated:\nNodes: "+(d+"\nElement: ")+(a.element.outerHTML+"\n"));return{X:d,element:a.element}}
function Xb(a,b,c){P(0!==a.length,"Trying to refine empty array of nodes");if(1>=a.length)var d=a;else{d=Wb(a,c);for(var e=[],f=0;f<a.length-1;f++){var h=e.concat(a.slice(f+1));Wb(h,c).length>d.length&&e.push(a[f])}e.push(a[a.length-1]);d=e}e=d;P(Wb(e,c).includes(b),"Removing redundant nodes does not resolve element anymore:\nInitial nodes: "+(a+"\nAfter refinement: ")+(e+"\n"));a=new X(e,[]);d=Yb(a,c);e=new X([],e);c=Yb(e,c);return c.includes(b)&&c.length<d.length?e:a}
function Vb(a,b){for(;null!==a&&b.contains(a)&&b!==a;){var c=dc(a);if(null!==c)return{node:c,element:a};a=a.parentElement}return null}function dc(a){if(vb(a))return null;var b=yb(a);return null===b?null:new Mb(b,[],Qa(a).name)}function Yb(a,b){b=Y(a,b);P(Gb(b),"Locator "+a+" didn't find any elements");return b.o}function Wb(a,b){a=new X(a,[]);return Yb(a,b)};function ec(a){return function(b){for(var c=[],d=0;d<arguments.length;++d)c[d-0]=arguments[d];try{return a.apply(null,ea(c))}catch(e){throw e instanceof K&&(e=Error(e.R+": "+e.message)),e;}}}function Z(a,b){"function"===typeof b&&(b=ec(b));window[a]=b}Z("findElementsBySemanticLocator",function(a,b){b=void 0===b?document.body:b;a=Y(Qb(a),b);return U(a)?[]:a.o});
Z("findElementBySemanticLocator",function(a,b){b=void 0===b?document.body:b;var c=Qb(a),d=Y(c,b);if(U(d)){a=Y(c,b,!0);a=U(a)?[]:a.o;b=Y(c,b,!1,!0);b=U(b)?[]:b.o;c="Didn't find any elements matching semantic locator "+c+". ";var e=d.u,f=d.F,h=d.C;d=d.A;var g=1<e.length;0===d.length?void 0===f?c+="No elements have "+W(h)+".":(c+=e.length+" element"+(g?"s":"")+" with "+(Hb(f)+" were found. "),c+="However "+(g?"none had":"it didn't have")+" "+(W(h)+". ")+(Ib(h,e)+".")):void 0===f?c+=e.length+" element"+
(g?"s":"")+" matched the locator "+(d.join(" ")+", but ")+((g?"none had":"it didn't have")+" a descendant with ")+(W(h)+"."):(c+=e.length+" descendant"+(g?"s":"")+" of "+(d.join(" ")+" with "+Hb(f)+" were found. "),c+="However "+(g?"none had":"it didn't have")+" "+(W(h)+". ")+(Ib(h,e)+"."));0<a.length&&(c+=" "+a.length+" hidden element"+((1<a.length?"s":"")+" matched the locator. To match these elements, ensure they're not hidden (aria-hidden is false and they're not hidden by css)."));0<b.length&&
(a=1<b.length,c+=" "+b.length+" element"+((a?"s":"")+" would have matched the locator, but ")+((a?"have":"it has")+" an ancestor with presentational children (https://www.w3.org/TR/wai-aria-practices/#children_presentational), erasing its semantics."));throw new Sa(c);}return d.o[0]});Z("closestPreciseLocatorFor",function(a,b){b=Tb(a,b);if(!b)return null;a=Ub(a,b);return null===a?null:Xb(a.X,a.element,b).toString()});
Z("preciseLocatorFor",function(a,b){b=Tb(a,b);if(!b)return null;var c=Ub(a,b);return null===c||c.element!==a?null:Xb(c.X,c.element,b).toString()});Z("closestSimpleLocatorFor",function(a,b){var c,d,e;return(b=Tb(a,b))?null!==(e=null===(d=null===(c=Vb(a,b))||void 0===c?void 0:c.node)||void 0===d?void 0:d.toString())&&void 0!==e?e:null:null});Z("simpleLocatorFor",function(a){var b,c;return null!==(c=null===(b=dc(a))||void 0===b?void 0:b.toString())&&void 0!==c?c:null});Z("semanticLocatorsReady",!0);}).call(this);
