(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},w="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");
},ca=ba(this),y=function(a,b){if(b)a:{var c=ca;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&w(c,a,{configurable:!0,writable:!0,value:b})}};
y("Symbol",function(a){if(a)return a;var b=function(f,g){this.Z=f;w(this,"description",{configurable:!0,writable:!0,value:g})};b.prototype.toString=function(){return this.Z};var c="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",d=0,e=function(f){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b(c+(f||"")+"_"+d++,f)};return e});
y("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=ca[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&w(d.prototype,a,{configurable:!0,writable:!0,value:function(){return da(aa(this))}})}return a});
var da=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a},z=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}},ea=function(a){if(!(a instanceof Array)){a=z(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a},ja="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},ka;
if("function"==typeof Object.setPrototypeOf)ka=Object.setPrototypeOf;else{var la;a:{var ma={a:!0},na={};try{na.__proto__=ma;la=na.a;break a}catch(a){}la=!1}ka=la?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var oa=ka,A=function(a,b){a.prototype=ja(b.prototype);a.prototype.constructor=a;if(oa)oa(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.ja=b.prototype},D=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};y("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});
y("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});var pa=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};
y("String.prototype.includes",function(a){return a?a:function(b,c){return-1!==pa(this,b,"includes").indexOf(b,c||0)}});y("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(h){return h};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof f){b=f.call(b);for(var g=0;!(f=b.next()).done;)e.push(c.call(d,f.value,g++))}else for(f=b.length,g=0;g<f;g++)e.push(c.call(d,b[g],g));return e}});
y("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)D(b,d)&&c.push([d,b[d]]);return c}});y("String.prototype.startsWith",function(a){return a?a:function(b,c){var d=pa(this,b,"startsWith");b+="";var e=d.length,f=b.length;c=Math.max(0,Math.min(c|0,d.length));for(var g=0;g<f&&c<e;)if(d[c++]!=b[g++])return!1;return g>=f}});
y("String.prototype.endsWith",function(a){return a?a:function(b,c){var d=pa(this,b,"endsWith");b+="";void 0===c&&(c=d.length);c=Math.max(0,Math.min(c|0,d.length));for(var e=b.length;0<e&&0<c;)if(d[--c]!=b[--e])return!1;return 0>=e}});var qa=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};
y("Array.prototype.values",function(a){return a?a:function(){return qa(this,function(b,c){return c})}});
y("WeakMap",function(a){function b(){}function c(m){var q=typeof m;return"object"===q&&null!==m||"function"===q}function d(m){if(!D(m,f)){var q=new b;w(m,f,{value:q})}}function e(m){var q=Object[m];q&&(Object[m]=function(u){if(u instanceof b)return u;Object.isExtensible(u)&&d(u);return q(u)})}if(function(){if(!a||!Object.seal)return!1;try{var m=Object.seal({}),q=Object.seal({}),u=new a([[m,2],[q,3]]);if(2!=u.get(m)||3!=u.get(q))return!1;u.delete(m);u.set(q,4);return!u.has(m)&&4==u.get(q)}catch(E){return!1}}())return a;
var f="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var g=0,h=function(m){this.K=(g+=Math.random()+1).toString();if(m){m=z(m);for(var q;!(q=m.next()).done;)q=q.value,this.set(q[0],q[1])}};h.prototype.set=function(m,q){if(!c(m))throw Error("Invalid WeakMap key");d(m);if(!D(m,f))throw Error("WeakMap key fail: "+m);m[f][this.K]=q;return this};h.prototype.get=function(m){return c(m)&&D(m,f)?m[f][this.K]:void 0};h.prototype.has=function(m){return c(m)&&D(m,f)&&D(m[f],this.K)};
h.prototype.delete=function(m){return c(m)&&D(m,f)&&D(m[f],this.K)?delete m[f][this.K]:!1};return h});
y("Map",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var h=Object.seal({x:4}),m=new a(z([[h,"s"]]));if("s"!=m.get(h)||1!=m.size||m.get({x:4})||m.set({x:4},"t")!=m||2!=m.size)return!1;var q=m.entries(),u=q.next();if(u.done||u.value[0]!=h||"s"!=u.value[1])return!1;u=q.next();return u.done||4!=u.value[0].x||"t"!=u.value[1]||!q.next().done?!1:!0}catch(E){return!1}}())return a;var b=new WeakMap,c=function(h){this.J={};this.B=f();
this.size=0;if(h){h=z(h);for(var m;!(m=h.next()).done;)m=m.value,this.set(m[0],m[1])}};c.prototype.set=function(h,m){h=0===h?0:h;var q=d(this,h);q.list||(q.list=this.J[q.id]=[]);q.m?q.m.value=m:(q.m={next:this.B,F:this.B.F,head:this.B,key:h,value:m},q.list.push(q.m),this.B.F.next=q.m,this.B.F=q.m,this.size++);return this};c.prototype.delete=function(h){h=d(this,h);return h.m&&h.list?(h.list.splice(h.index,1),h.list.length||delete this.J[h.id],h.m.F.next=h.m.next,h.m.next.F=h.m.F,h.m.head=null,this.size--,
!0):!1};c.prototype.clear=function(){this.J={};this.B=this.B.F=f();this.size=0};c.prototype.has=function(h){return!!d(this,h).m};c.prototype.get=function(h){return(h=d(this,h).m)&&h.value};c.prototype.entries=function(){return e(this,function(h){return[h.key,h.value]})};c.prototype.keys=function(){return e(this,function(h){return h.key})};c.prototype.values=function(){return e(this,function(h){return h.value})};c.prototype.forEach=function(h,m){for(var q=this.entries(),u;!(u=q.next()).done;)u=u.value,
h.call(m,u[1],u[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(h,m){var q=m&&typeof m;"object"==q||"function"==q?b.has(m)?q=b.get(m):(q=""+ ++g,b.set(m,q)):q="p_"+m;var u=h.J[q];if(u&&D(h.J,q))for(h=0;h<u.length;h++){var E=u[h];if(m!==m&&E.key!==E.key||m===E.key)return{id:q,list:u,index:h,m:E}}return{id:q,list:u,index:-1,m:void 0}},e=function(h,m){var q=h.B;return da(function(){if(q){for(;q.head!=h.B;)q=q.F;for(;q.next!=q.head;)return q=q.next,{done:!1,value:m(q)};q=null}return{done:!0,
value:void 0}})},f=function(){var h={};return h.F=h.next=h.head=h},g=0;return c});
y("Set",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),d=new a(z([c]));if(!d.has(c)||1!=d.size||d.add(c)!=d||1!=d.size||d.add({x:4})!=d||2!=d.size)return!1;var e=d.entries(),f=e.next();if(f.done||f.value[0]!=c||f.value[1]!=c)return!1;f=e.next();return f.done||f.value[0]==c||4!=f.value[0].x||f.value[1]!=f.value[0]?!1:e.next().done}catch(g){return!1}}())return a;var b=function(c){this.v=new Map;if(c){c=
z(c);for(var d;!(d=c.next()).done;)this.add(d.value)}this.size=this.v.size};b.prototype.add=function(c){c=0===c?0:c;this.v.set(c,c);this.size=this.v.size;return this};b.prototype.delete=function(c){c=this.v.delete(c);this.size=this.v.size;return c};b.prototype.clear=function(){this.v.clear();this.size=0};b.prototype.has=function(c){return this.v.has(c)};b.prototype.entries=function(){return this.v.entries()};b.prototype.values=function(){return this.v.values()};b.prototype.keys=b.prototype.values;
b.prototype[Symbol.iterator]=b.prototype.values;b.prototype.forEach=function(c,d){var e=this;this.v.forEach(function(f){return c.call(d,f,f,e)})};return b});y("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,f=0;f<e;f++){var g=d[f];if(b.call(c,g,f,d)){b=g;break a}}b=void 0}return b}});
y("Array.prototype.flatMap",function(a){return a?a:function(b,c){for(var d=[],e=0;e<this.length;e++){var f=b.call(c,this[e],e,this);Array.isArray(f)?d.push.apply(d,f):d.push(f)}return d}});/*

 Copyright 2020 Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
function ra(){return{h:{Y:[],M:[]}}};function sa(a){var b;return{W:null!==(b=a.W)&&void 0!==b?b:!1}};function ta(a,b){var c,d,e,f;return null!==(f=null!==(d=null===(c=a.matches)||void 0===c?void 0:c.call(a,b))&&void 0!==d?d:null===(e=a.msMatchesSelector)||void 0===e?void 0:e.call(a,b))&&void 0!==f?f:a.webkitMatchesSelector(b)}function F(a,b){if(a.closest)return a.closest(b);for(;!ta(a,b);){if(null===a.parentElement)return null;a=a.parentElement}return a};function H(a){return a.nodeType===Node.ELEMENT_NODE&&"http://www.w3.org/1999/xhtml"===a.namespaceURI}function ua(a){return a.nodeType===Node.ELEMENT_NODE&&"http://www.w3.org/2000/svg"===a.namespaceURI}function I(a,b){return a.tagName.toLowerCase()===b};function va(a){if(!H(a))return!1;if("hidden"===window.getComputedStyle(a).visibility||null!==F(a,'[hidden],[aria-hidden="true"]'))return!0;for(;null!==a;){if("none"===window.getComputedStyle(a).display)return!0;a=a.parentElement}return!1};function wa(a){var b,c,d=null!==(c=null===(b=a.getAttribute("aria-labelledby"))||void 0===b?void 0:b.split(" "))&&void 0!==c?c:[];a=[];d=z(d);for(var e=d.next();!e.done;e=d.next())(e=document.getElementById(e.value))&&a.push(e);return a};var ya=["email","tel","text","url","search"],za=["number","range"],Aa=["spinbutton","slider","progressbar","scrollbar"];
function Ba(a){var b,c=null!==(b=a.getAttribute("role"))&&void 0!==b?b:"",d=Aa.includes(c);if(c&&!d)return null;c=I(a,"input")&&za.includes(a.type)||I(a,"progress");if(d||c){if(a.hasAttribute("aria-valuetext"))return a.getAttribute("aria-valuetext");if(a.hasAttribute("aria-valuenow"))return a.getAttribute("aria-valuenow");if(I(a,"input"))return a.value;if(I(a,"progress"))return a.value.toString()}return null}
function Ca(a,b,c,d){var e=a.getAttribute("role");if(e&&"listbox"!==e&&"combobox"!==e)return null;if(I(a,"input")&&ya.includes(a.type)&&(a.hasAttribute("list")||"combobox"===e))return a.value;var f=[];e&&"listbox"===e?f=Array.from(a.querySelectorAll('[role="option"][aria-selected="true"]')):I(a,"select")&&(f=Array.from(a.selectedOptions));return 0<f.length?f.map(function(g){return d(g,b,{h:c.h}).name}).filter(function(g){return""!==g}).join(" "):null}
function Da(a,b,c,d){if(!H(a)||!c.h.I)return null;var e;return(e=(e=a.getAttribute("role"))&&"textbox"!==e?null:I(a,"textarea")||I(a,"input")&&ya.includes(a.type)&&!a.hasAttribute("list")?a.value:null)?e:(b=Ca(a,b,c,d))?b:(a=Ba(a))?a:null};var Ea="BUTTON INPUT METER OUTPUT PROGRESS SELECT TEXTAREA".split(" ");function Fa(a,b,c,d){return Array.from(document.querySelectorAll("label")).filter(function(e){return void 0!==e.control?e.control===a:""!==e.htmlFor&&e.htmlFor===a.id?!0:""===e.htmlFor&&e.contains(a)?!0:!1}).map(function(e){return d(e,b,{O:!0,h:c.h}).name}).filter(function(e){return""!==e}).join(" ")||null};var Ga={T:"button cell checkbox columnheader gridcell heading link menuitem menuitemcheckbox menuitemradio option radio row rowgroup rowheader switch tab tooltip tree treeitem".split(" "),tags:"button h1 h2 h3 h4 h5 h6 summary tbody tfoot thead".split(" ")},Ha={T:"alert alertdialog application article banner complementary dialog document feed figure form grid group img listbox log main marquee math menu menubar navigation radiogroup region scrollbar search searchbox separator slider spinbutton tablist tabpanel textbox timer toolbar treegrid".split(" "),
tags:"article aside body datalist dialog fieldset figure footer form header hr img input main math menu nav optgroup section select textarea".split(" ")},Ia={T:"contentinfo definition directory list note status table term".split(" "),tags:"dd details dl ol output table ul".split(" ")};
function Ja(a){switch(a){case "th":return function(b){return null!==F(b,"table")};case "td":return function(b){return null!==F(b,"table")};case "option":return function(b){return null!==F(b,"select,datalist")};case "a":return function(b){return b.hasAttribute("href")};case "area":return function(b){return b.hasAttribute("href")};case "link":return function(b){return b.hasAttribute("href")};default:return null}}
function J(a,b){var c,d,e=null!==(d=null===(c=a.getAttribute("role"))||void 0===c?void 0:c.trim().toLowerCase())&&void 0!==d?d:"";return b.T.includes(e)||b.tags.includes(a.nodeName.toLowerCase())?!0:!1}
function Ka(a,b){var c;if(b.h.I&&a.parentElement&&J(a.parentElement,Ga)&&J(a,Ia))return!0;if(J(a,Ha))return"menu"===(null===(c=a.getAttribute("role"))||void 0===c?void 0:c.toLowerCase())?!1:(I(a,"a")||I(a,"area")||I(a,"link"))&&a.hasAttribute("href")||(I(a,"input")||I(a,"select")||I(a,"textarea")||I(a,"button"))&&!a.hasAttribute("disabled")?!0:a.hasAttribute("tabindex")||a.isContentEditable;if(J(a,Ga))return!0;var d=Ja(a.nodeName.toLowerCase());return d&&d(a)||b.O||b.h.I?!0:!1}
function La(a,b){b=window.getComputedStyle(a,b);a=b.content;b="block"===b.display;return'"'===a[0]&&'"'===a[a.length-1]||"'"===a[0]&&"'"===a[a.length-1]?b?" "+a.slice(1,-1)+" ":a.slice(1,-1):""}var Ma="a abbr acronym b bdi bdo big button canvas cite code data datalist del dfn em embed i iframe img ins kbd label map mark meter noscript object output picture progress q ruby s samp script select slot small span strong sub sup template textarea time tt u var video wbr".split(" ");var Na="text password search tel email url".split(" ");var Oa={"2A":function(a,b,c){b=null;va(a)&&!c.O&&(b="");return b},"2B":function(a,b,c,d){if(!H(a)||c.O)return null;a=wa(a);return 0===a.length?null:a.map(function(e){c.h.I=!0;return d(e,b,{O:!0,h:c.h}).name}).join(" ").trim()},"2C":function(a,b,c,d){var e;if(a.nodeType!==Node.ELEMENT_NODE)return null;var f=null!==(e=a.getAttribute("aria-label"))&&void 0!==e?e:"";return""===f.trim()?null:c.h.I&&(a=Da(a,b,{h:c.h},d),null!==a)?a:f},"2D":function(a,b,c,d){if(ua(a))for(var e=z(a.childNodes),f=e.next();!f.done;f=
e.next())if(f=f.value,ua(f)&&I(f,"title"))return f.textContent;(e=!H(a))||(e=a.getAttribute("role"),e="presentation"===e||"none"===e||null===e&&I(a,"img")&&""===a.getAttribute("alt")?!0:!1);if(e)return null;if(Ea.includes(a.tagName)&&(e=Fa(a,b,c,d)))return e;if(I(a,"input")){var g;e=null!==(g=a.getAttribute("type"))&&void 0!==g?g:"";if(g="button"!==e&&"submit"!==e&&"reset"!==e||!a.hasAttribute("value")?"submit"===e||"reset"===e?e:"image"===e&&a.hasAttribute("alt")?a.getAttribute("alt"):"image"!==
e||a.hasAttribute("title")?null:"Submit Query":a.value)return g}return I(a,"table")&&(g=a.querySelector("caption"))?(c.h.I=!0,d(g,b,{h:c.h}).name):I(a,"figure")&&(g=a.querySelector("figcaption"))?(c.h.I=!0,d(g,b,{h:c.h}).name):I(a,"fieldset")&&(g=a.querySelector("legend"))?(c.h.I=!0,d(g,b,{h:c.h}).name):(b=a.getAttribute("alt"))&&(I(a,"img")||I(a,"area"))?b:null},"2E":Da,"2F":function(a,b,c,d){if(!H(a)||!Ka(a,c))return null;var e=Array.from(a.childNodes),f=a.getAttribute("aria-owns");if(f){f=z(f.split(" "));
for(var g=f.next();!g.done;g=f.next())(g=document.getElementById(g.value))&&e.push(g)}f=[];e=z(e);for(g=e.next();!g.done;g=e.next())if(g=g.value,!c.h.Y.includes(g)){c.h.Y.push(g);c.h.I=!0;var h=d(g,b,{h:c.h}).name;Ma.includes(g.nodeName.toLowerCase())||g.nodeType===Node.TEXT_NODE?f.push(h):f.push(" "+h+" ")}b.W&&(f.unshift(La(a,":before")),f.push(La(a,":after")));a=f.join("");return""===a.trim()?null:a},"2G":function(a){return a.nodeType===Node.TEXT_NODE?a.data:null},"2I":function(a){return H(a)?
a.title?a.title:I(a,"input")&&Na.includes(a.type)?a.placeholder:I(a,"textarea")&&a.hasAttribute("placeholder")?a.getAttribute("placeholder"):null:null}};function Pa(a,b,c){b=void 0===b?sa({}):b;c=void 0===c?ra():c;for(var d=z(Object.entries(Oa)),e=d.next();!e.done;e=d.next()){var f=z(e.value);e=f.next().value;f=f.next().value;f=f(a,b,c,Pa);if(null!==f)return b=f.replace(/\s+/g," "),c.h.M.push({ia:e,node:a,text:b}),{name:b,M:c.h.M}}return{name:"",M:c.h.M}};function Qa(a){var b=void 0===b?{}:b;b=void 0===b?{}:b;var c=void 0===c?ra():c;return Pa(a,sa(b),c).name.trim()};/*

 Copyright 2021 The Semantic Locators Authors
 SPDX-License-Identifier: Apache-2.0
*/
var K=function(){var a=Error.apply(this,arguments);this.message=a.message;"stack"in a&&(this.stack=a.stack);this.P="SemanticLocatorError"};A(K,Error);var Ra=function(){K.apply(this,arguments);this.P="NoSuchElementError"};A(Ra,K);var Sa=function(){K.apply(this,arguments);this.P="ValueError"};A(Sa,K);var L=function(){K.apply(this,arguments);this.P="InvalidLocatorError"};A(L,K);function Ta(a){return Qa(a)};var Ua="checked current disabled selected colindex level posinset readonly rowindex".split(" ");var Va=new Set("alert alertdialog application directory feed grid log marquee menu menubar menuitem menuitemcheckbox menuitemradio note radiogroup scrollbar search switch tab tablist tabpanel timer toolbar tooltip tree treegrid treeitem".split(" ")),Wa="button checkbox img math menuitemcheckbox menuitemradio progressbar radio scrollbar separator slider switch tab".split(" "),M={article:{g:"article"},banner:{l:[{j:"header",conditions:[{type:1,V:'article,aside,main,nav,section,[role="article"],[role="complementary"],[role="main"],[role="navigation"],[role="region"]'}]}]},
button:{g:"button,summary",l:[{j:"input",conditions:[{type:5,propertyName:"type",values:["button","image","reset","submit"]}]}]},cell:{l:[{j:"td",conditions:[{type:6,tag:"table",i:"table"}]},{j:'th:not([scope="col"]):not([scope="colgroup"]):not([scope="row"]):not([scope="rowgroup"])',conditions:[{type:6,tag:"table",i:"table"},{type:8,S:!0},{type:7,N:!0}]}]},checkbox:{l:[{j:"input",conditions:[{type:5,propertyName:"type",values:["checkbox"]}]}]},columnheader:{g:'th[scope="col"],th[scope="colgroup"]',
l:[{j:'th:not([scope="col"]):not([scope="colgroup"]):not([scope="row"]):not([scope="rowgroup"])',conditions:[{type:7,N:!1}]}]},combobox:{g:"select:not([multiple]):not([size])",l:[{j:"select:not([multiple])",conditions:[{type:3,s:"size",value:2}]},{j:"input[list]",conditions:[{type:5,propertyName:"type",values:["email","search","tel","text","url"]}]}]},complementary:{g:"aside"},contentinfo:{l:[{j:"footer",conditions:[{type:1,V:'article,aside,main,nav,section,[role="article"],[role="complementary"],[role="main"],[role="navigation"],[role="region"]'}]}]},
definition:{g:"dd"},dialog:{g:"dialog"},document:{g:"body"},figure:{g:"figure"},form:{l:[{j:"form",conditions:[{type:4}]}]},gridcell:{l:[{j:"td",conditions:[{type:6,tag:"table",i:"grid"}]},{j:"td",conditions:[{type:6,tag:"table",i:"treegrid"}]},{j:'th:not([scope="col"]):not([scope="colgroup"]):not([scope="row"]):not([scope="rowgroup"])',conditions:[{type:6,tag:"table",i:"treegrid"},{type:8,S:!0},{type:7,N:!0}]}]},group:{g:"details,fieldset,optgroup"},heading:{g:"h1,h2,h3,h4,h5,h6"},img:{g:'img:not([alt]),img[alt]:not([alt=""])'},
link:{g:"a[href],area[href],link[href]"},list:{g:"menu,ol,ul"},listbox:{g:"datalist,select[multiple]",l:[{j:"select",conditions:[{type:2,s:"size",value:1}]}]},listitem:{g:"li"},main:{g:"main"},math:{g:"math"},navigation:{g:"nav"},option:{g:"datalist > option,select > optgroup > option,select > option"},progressbar:{g:"progress"},radio:{l:[{j:"input",conditions:[{type:5,propertyName:"type",values:["radio"]}]}]},region:{l:[{j:"section",conditions:[{type:4}]}]},row:{g:"tr"},rowgroup:{g:"tbody,tfoot,thead"},
rowheader:{g:'th[scope="row"],th[scope="rowgroup"]',l:[{j:'th:not([scope="col"]):not([scope="colgroup"]):not([scope="row"]):not([scope="rowgroup"])',conditions:[{type:8,S:!1},{type:7,N:!0}]}]},searchbox:{l:[{j:"input:not([list])",conditions:[{type:5,propertyName:"type",values:["search"]}]}]},separator:{g:"hr"},slider:{l:[{j:"input",conditions:[{type:5,propertyName:"type",values:["range"]}]}]},spinbutton:{l:[{j:"input",conditions:[{type:5,propertyName:"type",values:["number"]}]}]},status:{g:"output"},
table:{g:"table"},term:{g:"dfn,dt"},textbox:{g:"textarea",l:[{j:"input:not([list])",conditions:[{type:5,propertyName:"type",values:["email","tel","text","url"]}]}]}},Xa={a:["link"],area:["link"],article:["article"],aside:["complementary"],body:["document"],button:["button"],datalist:["listbox"],dd:["definition"],details:["group"],dfn:["term"],dialog:["dialog"],dt:["term"],fieldset:["group"],figure:["figure"],footer:["contentinfo"],form:["form"],h1:["heading"],h2:["heading"],h3:["heading"],h4:["heading"],
h5:["heading"],h6:["heading"],header:["banner"],hr:["separator"],img:["img"],input:"button checkbox combobox radio searchbox slider spinbutton textbox".split(" "),li:["listitem"],link:["link"],main:["main"],math:["math"],menu:["list"],nav:["navigation"],ol:["list"],optgroup:["group"],option:["option"],output:["status"],progress:["progressbar"],section:["region"],select:["combobox","listbox"],summary:["button"],table:["table"],tbody:["rowgroup"],td:["cell","gridcell"],textarea:["textbox"],tfoot:["rowgroup"],
th:["cell","columnheader","gridcell","rowheader"],thead:["rowgroup"],tr:["row"],ul:["list"]},Ya=["none","presentation"];function Za(a){throw Error("unexpected value "+a+"!");}function $a(a){if(ab())for(var b=1;b<a.length;b++)if(0<N(a[b-1],a[b]))throw Error("Elements not passed in document order. Index "+(b-1)+" comes after index "+(b+". Elements: "+JSON.stringify(a)));}function N(a,b){return a===b?0:a.compareDocumentPosition(b)&Node.DOCUMENT_POSITION_PRECEDING?1:-1}function bb(a){return a.filter(function(b,c){return a[c-1]!==b})}function O(a,b){return a.tagName.toLowerCase()===b}
function P(a,b){if(ab()&&!a)throw a="Assertion failed",void 0!==b&&(a+=": "+b),Error(a);}function ab(){var a,b;return(null===(b=null===(a=window)||void 0===a?void 0:a.ha)||void 0===b?void 0:b.fa)||!1};function cb(a,b){a=db(a);b=eb(a,b);return a.cells.slice(b.da,b.ba+1).some(function(c){return c.some(Q)})}function pb(a,b){a=db(a);b=eb(a,b);var c=b.ca,d=b.aa;return a.cells.some(function(e){return e.slice(c,d+1).some(Q)})}
var R=function(a){this.cells=a=void 0===a?[]:a},qb=function(a,b,c){return S(a,c)[b]},S=function(a,b){void 0===a.cells[b]&&(a.cells[b]=[]);return a.cells[b]},eb=function(a,b){for(var c=a.width,d=a.height,e=-1,f=-1,g=0;g<a.height;g++){var h=S(a,g),m=h.indexOf(b);-1!==m&&(e=Math.max(e,h.lastIndexOf(b)),f=Math.max(f,g),c=Math.min(c,m),d=Math.min(d,g))}P(e<a.width&&f<a.height&&-1<c&&-1<d,"Target cell not found in table");return{ca:c,da:d,aa:e,ba:f}};R.prototype.concat=function(a){this.cells=this.cells.concat(a.cells)};
ca.Object.defineProperties(R.prototype,{height:{configurable:!0,enumerable:!0,get:function(){return this.cells.length}},width:{configurable:!0,enumerable:!0,get:function(){return Math.max.apply(Math,ea(this.cells.map(function(a){return a.length})))}}});
function db(a){var b=new R;null!==a.tHead&&b.concat(rb(a.tHead.rows));for(var c=z(a.tBodies),d=c.next();!d.done;d=c.next())b.concat(rb(d.value.rows));c=[];d=z(a.children);for(var e=d.next();!e.done;e=d.next())e=e.value,e.nodeType===Node.ELEMENT_NODE&&"http://www.w3.org/1999/xhtml"===e.namespaceURI&&O(e,"tr")&&c.push(e);b.concat(rb(c));null!==a.tFoot&&b.concat(rb(a.tFoot.rows));return b}
function rb(a){for(var b=new R,c=[],d=0;d<a.length;d++){for(var e=0,f=z(a[d].cells),g=f.next();!g.done;g=f.next()){for(g=g.value;qb(b,e,d)||c[e];){if(!Q(qb(b,e,d))&&c[e]){var h=e,m=c[e];S(b,d)[h]=m}e++}for(h=e;h<e+g.colSpan;h++)for(0===sb(g)&&(c[h]=g,m=h,S(b,d)[m]=g),m=d;m<d+sb(g);m++)if(!Q(qb(b,h,m))){var q=h;S(b,m)[q]=g}e+=g.colSpan}for(;e<b.width;e++)f=c[e],void 0===f||Q(qb(b,e,d))||(g=e,S(b,d)[g]=f)}return b}
function sb(a){a=a.getAttribute("rowSpan");if(null===a||""===a.trim())return 1;a=Number(a);return isNaN(a)?1:a}function Q(a){return void 0!==a&&O(a,"td")};function tb(a,b,c,d){var e,f=Array.from(b.querySelectorAll('[role="'+a+'"]'));if(Va.has(a))return f.filter(function(m){return c||!ub(m)}).filter(function(m){return d||!vb(m)});f=new Set(f);a=M[a];var g=a.g;if(g){g=wb(g,b);var h=z(g);for(g=h.next();!g.done;g=h.next())f.add(g.value)}a=z(null!==(e=a.l)&&void 0!==e?e:[]);for(g=a.next();!g.done;g=a.next())for(g=g.value,g=wb(g.j,b,g.conditions),h=z(g),g=h.next();!g.done;g=h.next())f.add(g.value);return Array.from(f).filter(function(m){return c||!ub(m)}).filter(function(m){return d||
!vb(m)}).sort(N)}function xb(a){var b,c=a.getAttribute("role");if(c){if(Ya.includes(c))return null;if(Va.has(c)||M.hasOwnProperty(c))return c}return(null!==(b=Xa[a.tagName.toLowerCase()])&&void 0!==b?b:[]).find(function(d){return yb(a,d)})||null}function ub(a){if("hidden"===window.getComputedStyle(a).visibility||null!==T(a,'[aria-hidden="true"]'))return!0;for(;null!==a;){if("none"===window.getComputedStyle(a).display)return!0;a=a.parentElement}return!1}
function zb(a,b){switch(b.type){case 2:var c=a.getAttribute(b.s);return null!==c&&Number(c)>b.value;case 3:return c=a.getAttribute(b.s),null!==c&&Number(c)<b.value;case 4:return a.hasAttribute("aria-label")||a.hasAttribute("aria-labelledby")&&a.getAttribute("aria-labelledby").split(" ").some(function(d){return void 0!==document.getElementById(d)});case 1:return null===T(a,b.V);case 0:return a[b.propertyName]===b.value;case 5:return b.values.some(function(d){return d===a[b.propertyName]});case 6:c=
a.parentElement;if(null===c)return!1;c=T(c,b.tag);return null!==c&&xb(c)===b.i;case 8:return c=T(a,"table"),null===c?!1:b.S===pb(c,a);case 7:return c=T(a,"table"),null===c?!1:b.N===cb(c,a);default:Za(b)}}function Ab(a,b,c){var d=Bb(a.parentElement,b);return null===d?null:c.flatMap(function(e){return tb(e,d,!1,!1)}).filter(function(e){return d===Bb(e.parentElement,b)}).sort(N).indexOf(a)+1||null}
function yb(a,b){var c,d;b=M[b];var e=b.g;return e&&Cb(a,e)?!0:null!==(d=null===(c=b.l)||void 0===c?void 0:c.some(function(f){return Cb(a,f.j)&&f.conditions.every(function(g){return zb(a,g)})}))&&void 0!==d?d:!1}function vb(a){for(var b=z(Wa),c=b.next();!c.done;c=b.next())if(null!==Bb(a.parentElement,c.value))return!0;return!1}
function Bb(a,b){var c,d='[role="'+b+'"]';if(M.hasOwnProperty(b)){var e=M[b];void 0!==e.g&&(d+=","+Db(e.g));for(var f=z(null!==(c=e.l)&&void 0!==c?c:[]),g=f.next();!g.done;g=f.next())if("input"!==g.value.j)throw Error("Not implemented: closestWithRole called with a role which requires a condition to be checked. Role: "+b+"; Selector: "+e);}return T(a,d)}function wb(a,b,c){a=Array.from(b.querySelectorAll(Db(a)));return c?a.filter(function(d){return c.every(function(e){return zb(d,e)})}):a}
function Db(a){return a.split(",").map(function(b){return b+":not([role])"}).join(",")}function Cb(a,b){var c,d,e,f;return null!==(f=null!==(d=null===(c=a.matches)||void 0===c?void 0:c.call(a,b))&&void 0!==d?d:null===(e=a.msMatchesSelector)||void 0===e?void 0:e.call(a,b))&&void 0!==f?f:a.webkitMatchesSelector(b)}function T(a,b){if(a.closest)return a.closest(b);for(;!Cb(a,b);){if(null===a.parentElement)return null;a=a.parentElement}return a};function Eb(a,b){if(a.hasAttribute("aria-"+b))return a.getAttribute("aria-"+b);switch(b){case "checked":return O(a,"input")&&["checkbox","radio"].includes(a.type)?a.checked.toString():null;case "current":return"false";case "disabled":return((O(a,"button")||O(a,"fieldset")||O(a,"input")||O(a,"optgroup")||O(a,"option")||O(a,"select")||O(a,"textarea"))&&a.disabled).toString();case "selected":return O(a,"option")?a.selected.toString():null;case "colindex":return(a=Ab(a,"row",["columnheader","cell"]))?
String(a):null;case "level":return a=a.tagName.match(/^H([1-6])$/),null===a?null:a[1];case "rowindex":return(a=Ab(a,"table",["row"]))?String(a):null;case "posinset":return b=xb(a),"listitem"===b?(a=Ab(a,"list",["listitem"]))?String(a):null:"treeitem"===b?(a=Ab(a,"tree",["treeitem"]))?String(a):null:null;case "readonly":return(O(a,"input")&&a.readOnly||"false"===a.contentEditable).toString();default:Za(b)}};function V(a){return void 0!==a.u}function Fb(a){return void 0!==a.o}function W(a){return void 0!==a.i?"an ARIA role of "+a.i:void 0!==a.s?"aria-"+a.s.name+" = "+a.s.value:'an accessible name of "'+a.name+'"'}function Gb(a){var b,c=[];a.i&&c.push(W({i:a.i}));a.attributes&&(c=c.concat(a.attributes.map(function(d){return W({s:d})})));a.name&&c.push(W({name:a.name}));return 1>=c.length?null!==(b=c[0])&&void 0!==b?b:"":c.slice(0,c.length-1).join(", ")+(", and "+c[c.length-1])}
function Hb(a,b){if(void 0!==a.i)return b=b.map(function(c){return xb(c)}).filter(function(c){return null!=c}),"Roles found: "+JSON.stringify(Array.from(new Set(b)));if(void 0!==a.s)return b=b.map(function(c){return Eb(c,a.s.name)}),"Values found for aria-"+a.s.name+": "+JSON.stringify(Array.from(new Set(b)));b=b.map(Ta).filter(function(c){return""!==c});return 0===b.length?"No matching elements had an accessible name":"Accessible names found: "+JSON.stringify(Array.from(new Set(b)))}
function Ib(a){var b=a.map(Jb),c=Math.max.apply(Math,ea(b));a=a.filter(function(d,e){return b[e]===c});return{u:bb(a.flatMap(function(d){return d.u}).sort(N)),A:a[0].A,D:a[0].D,C:a[0].C}}function Jb(a){var b,c=a.A.length;a=null!==(b=a.D)&&void 0!==b?b:{};var d=0;void 0!==a.i&&d++;void 0!==a.attributes&&(d+=a.attributes.length);void 0!==a.name&&d++;return c+d/50};function Kb(a){$a(a);if(0===a.length)return[];var b=[a[0]];a=z(a);for(var c=a.next();!c.done;c=a.next())c=c.value,b[b.length-1].contains(c)||b.push(c);return b};var X=function(a,b){this.R=a;this.L=b;a=a.concat(b);b=z(a);for(var c=b.next();!c.done;c=b.next()){c=c.value;var d=c.i;if(!Va.has(d)&&!M.hasOwnProperty(d))throw new L("Invalid locator: "+this+(" Unknown role: "+c.i+". The list of valid roles can be found at https://www.w3.org/TR/wai-aria/#role_definitions"));if(c!==a[a.length-1]&&Wa.includes(c.i))throw new L("Invalid locator: "+this+(' The role "'+c.i+'" has presentational children. That means its descendants cannot have semantics, so an element with a role of ')+
(c.i+" may only be the final element of a Semantic Locator. https://www.w3.org/TR/wai-aria-practices/#children_presentational"));c=z(c.attributes);for(d=c.next();!d.done;d=c.next())if(d=d.value,!Ua.includes(d.name))throw new L("Invalid locator: "+this+(" Unsupported attribute: "+d.name+". Supported attributes: ")+Ua);}};
X.prototype.toString=function(){for(var a=[],b=z(this.R),c=b.next();!c.done;c=b.next())a.push(c.value.toString());if(0<this.L.length)for(a.push("outer"),b=z(this.L),c=b.next();!c.done;c=b.next())a.push(c.value.toString());return a.join(" ")};var Lb=function(a,b,c){this.i=a;this.attributes=b;this.name=c};
Lb.prototype.toString=function(){var a="{"+this.i;if(this.name){a+=" ";var b=this.name;b=b.includes("'")&&!b.includes('"')?JSON.stringify(b):"'"+b.replace(/'/g,"\\'")+"'";a+=b}b=z(this.attributes);for(var c=b.next();!c.done;c=b.next())c=c.value,a+=" "+c.name+":"+c.value;return a+"}"};var Mb=function(a,b,c,d){b=Error.call(this);this.message=b.message;"stack"in b&&(this.stack=b.stack);this.message=a;this.o=c;this.location=d;this.name="SyntaxError";"function"===typeof Error.captureStackTrace&&Error.captureStackTrace(this,Mb)};A(Mb,Error);
var Nb=function(a,b){function c(g){return g.charCodeAt(0).toString(16).toUpperCase()}function d(g){return g.replace(/\\/g,"\\\\").replace(/"/g,'\\"').replace(/\0/g,"\\0").replace(/\t/g,"\\t").replace(/\n/g,"\\n").replace(/\r/g,"\\r").replace(/[\x00-\x0F]/g,function(h){return"\\x0"+c(h)}).replace(/[\x10-\x1F\x7F-\x9F]/g,function(h){return"\\x"+c(h)})}function e(g){return g.replace(/\\/g,"\\\\").replace(/\]/g,"\\]").replace(/\^/g,"\\^").replace(/-/g,"\\-").replace(/\0/g,"\\0").replace(/\t/g,"\\t").replace(/\n/g,
"\\n").replace(/\r/g,"\\r").replace(/[\x00-\x0F]/g,function(h){return"\\x0"+c(h)}).replace(/[\x10-\x1F\x7F-\x9F]/g,function(h){return"\\x"+c(h)})}function f(g){switch(g.type){case "literal":return'"'+d(g.text)+'"';case "class":var h=g.ea.map(function(m){return Array.isArray(m)?e(m[0])+"-"+e(m[1]):e(m)});return"["+(g.$?"^":"")+h+"]";case "any":return"any character";case "end":return"end of input";case "other":return g.description}}return"Expected "+function(g){g=g.map(f);var h,m;g.sort();if(0<g.length){for(m=
h=1;h<g.length;h++)g[h-1]!==g[h]&&(g[m]=g[h],m++);g.length=m}switch(g.length){case 1:return g[0];case 2:return g[0]+" or "+g[1];default:return g.slice(0,-1).join(", ")+", or "+g[g.length-1]}}(a)+" but "+(b?'"'+d(b)+'"':"end of input")+" found."};
function Ob(a){function b(l,p){return{type:"literal",text:l,ignoreCase:p}}function c(l,p,r){return{type:"class",ea:l,$:p,ignoreCase:r}}function d(l){var p=fa[l],r;if(!p){for(r=l-1;!fa[r];)r--;p=fa[r];for(p={line:p.line,H:p.H};r<l;)10===a.charCodeAt(r)?(p.line++,p.H=1):p.H++,r++;fa[l]=p}return p}function e(l,p){var r=d(l),t=d(p);return{start:{offset:l,line:r.line,H:r.H},end:{offset:p,line:t.line,H:t.H}}}function f(l){n<B||(n>B&&(B=n,xa=[]),xa.push(l))}function g(){var l;var p=n;var r=[];for(l=h();l!==
k;)r.push(l),l=h();if(r!==k){l=n;if("outer"===a.substr(n,5)){var t="outer";n+=5}else t=k,0===v&&f(Yb);t===k&&(t=null);if(t!==k)if(t=G(),t!==k){t=[];var x=h();if(x!==k)for(;x!==k;)t.push(x),x=h();else t=k;t!==k?l=t:(n=l,l=k)}else n=l,l=k;else n=l,l=k;l===k&&(l=null);l!==k?(p=l||[],p=r=new X(r,p)):(n=p,p=k)}else n=p,p=k;return p}function h(){var l;var p=n;if(123===a.charCodeAt(n)){var r="{";n++}else r=k,0===v&&f(Zb);if(r!==k)if(r=G(),r!==k)if(r=q(),r!==k){var t=G();if(t!==k){t=n;if(34===a.charCodeAt(n)){var x=
'"';n++}else x=k,0===v&&f(ha);if(x!==k){x=[];for(l=u();l!==k;)x.push(l),l=u();x!==k?(34===a.charCodeAt(n)?(l='"',n++):(l=k,0===v&&f(ha)),l!==k?t=x=x.join(""):(n=t,t=k)):(n=t,t=k)}else n=t,t=k;if(t===k)if(t=n,39===a.charCodeAt(n)?(x="'",n++):(x=k,0===v&&f(ia)),x!==k){x=[];for(l=E();l!==k;)x.push(l),l=E();x!==k?(39===a.charCodeAt(n)?(l="'",n++):(l=k,0===v&&f(ia)),l!==k?t=x=x.join(""):(n=t,t=k)):(n=t,t=k)}else n=t,t=k;t===k&&(t=null);if(t!==k)if(x=G(),x!==k){x=[];for(l=m();l!==k;)x.push(l),l=m();x!==
k?(l=G(),l!==k?(125===a.charCodeAt(n)?(l="}",n++):(l=k,0===v&&f($b)),l!==k?(l=G(),l!==k?p=r=t?new Lb(r,x,t):new Lb(r,x):(n=p,p=k)):(n=p,p=k)):(n=p,p=k)):(n=p,p=k)}else n=p,p=k;else n=p,p=k}else n=p,p=k}else n=p,p=k;else n=p,p=k;else n=p,p=k;return p}function m(){var l=n;var p=G();if(p!==k)if(p=q(),p!==k){if(58===a.charCodeAt(n)){var r=":";n++}else r=k,0===v&&f(ac);if(r!==k){r=[];if(fb.test(a.charAt(n))){var t=a.charAt(n);n++}else t=k,0===v&&f(gb);if(t!==k)for(;t!==k;)r.push(t),fb.test(a.charAt(n))?
(t=a.charAt(n),n++):(t=k,0===v&&f(gb));else r=k;r!==k&&(r=r.join(""));r!==k?(t=G(),t!==k?l=p={name:p,value:r}:(n=l,l=k)):(n=l,l=k)}else n=l,l=k}else n=l,l=k;else n=l,l=k;return l}function q(){var l=[];if(hb.test(a.charAt(n))){var p=a.charAt(n);n++}else p=k,0===v&&f(ib);if(p!==k)for(;p!==k;)l.push(p),hb.test(a.charAt(n))?(p=a.charAt(n),n++):(p=k,0===v&&f(ib));else l=k;l!==k&&(l=l.join(""));return l}function u(){var l;var p=l=n;v++;if(34===a.charCodeAt(n)){var r='"';n++}else r=k,0===v&&f(ha);r===k&&
(92===a.charCodeAt(n)?(r="\\",n++):(r=k,0===v&&f(U)));v--;r===k?p=void 0:(n=p,p=k);p!==k?(a.length>n?(r=a.charAt(n),n++):(r=k,0===v&&f(jb)),r!==k?l=r:(n=l,l=k)):(n=l,l=k);l===k&&(l=n,92===a.charCodeAt(n)?(p="\\",n++):(p=k,0===v&&f(U)),p!==k?(r=kb(),r!==k?l=r:(n=l,l=k)):(n=l,l=k));return l}function E(){var l;var p=l=n;v++;if(39===a.charCodeAt(n)){var r="'";n++}else r=k,0===v&&f(ia);r===k&&(92===a.charCodeAt(n)?(r="\\",n++):(r=k,0===v&&f(U)));v--;r===k?p=void 0:(n=p,p=k);p!==k?(a.length>n?(r=a.charAt(n),
n++):(r=k,0===v&&f(jb)),r!==k?l=r:(n=l,l=k)):(n=l,l=k);l===k&&(l=n,92===a.charCodeAt(n)?(p="\\",n++):(p=k,0===v&&f(U)),p!==k?(r=kb(),r!==k?l=r:(n=l,l=k)):(n=l,l=k));return l}function kb(){if(39===a.charCodeAt(n)){var l="'";n++}else l=k,0===v&&f(ia);l===k&&(34===a.charCodeAt(n)?(l='"',n++):(l=k,0===v&&f(ha)),l===k&&(92===a.charCodeAt(n)?(l="\\",n++):(l=k,0===v&&f(U))));return l}function G(){v++;var l=[];if(lb.test(a.charAt(n))){var p=a.charAt(n);n++}else p=k,0===v&&f(mb);for(;p!==k;)l.push(p),lb.test(a.charAt(n))?
(p=a.charAt(n),n++):(p=k,0===v&&f(mb));v--;l===k&&0===v&&f(bc);return l}var C=void 0!==C?C:{};var k={},nb={ga:g},ob=g,Yb=b("outer",!1),Zb=b("{",!1),$b=b("}",!1),ac=b(":",!1),hb=/^[a-z]/,ib=c([["a","z"]],!1,!1),fb=/^[a-z0-9_]/,gb=c([["a","z"],["0","9"],"_"],!1,!1),ha=b('"',!1),ia=b("'",!1),U=b("\\",!1),jb={type:"any"},bc={type:"other",description:"space"},lb=/^[ \t]/,mb=c([" ","\t"],!1,!1),n=0,fa=[{line:1,H:1}],B=0,xa=[],v=0;if(void 0!==C.U){if(!(C.U in nb))throw Error("Can't start parsing from rule \""+
C.U+'".');ob=nb[C.U]}C=ob();if(C!==k&&n===a.length)return C;C!==k&&n<a.length&&f({type:"end"});throw function(l,p,r){return new Mb(Nb(l,p),l,p,r)}(xa,B<a.length?a.charAt(B):null,B<a.length?e(B,B+1):e(B,B));};function Pb(a){var b;try{var c=Ob(a)}catch(d){if(d instanceof L)throw d;throw new L('Failed to parse semantic locator "'+a+'". '+(null!==(b=d.message)&&void 0!==b?b:d));}if(ab()&&!(c instanceof X))throw Error("parse("+a+") didn't return a SemanticLocator. Return value "+JSON.stringify(c));a=c;if(0===a.R.length&&0===a.L.length)throw new L("Locator is empty");return a};function Y(a,b,c,d){b=void 0===b?document.body:b;c=void 0===c?!1:c;d=void 0===d?!1:d;b=Qb(a.R,[b],c,d);if(V(b)||0===a.L.length)return b;b=b.o.map(function(f){return Qb(a.L,[f],c,d)});var e=b.filter(Fb).flatMap(function(f){return Kb(f.o)});return 0===e.length?(b=Ib(b),{A:a.R.concat(b.A),u:b.u,C:b.C,D:b.D}):{o:bb(e.sort(N))}}function Qb(a,b,c,d){for(var e=0;e<a.length;e++){b=Rb(a[e],b,c,d);if(V(b))return{A:a.slice(0,e),u:b.u,C:b.C,D:b.D};b=b.o}return{o:b}}
function Rb(a,b,c,d){b=Kb(b);var e=b.flatMap(function(h){return tb(a.i,h,c,d)});if(0===e.length)return{A:[],u:b,C:{i:a.i}};var f=a.attributes;for(b={G:0};b.G<f.length;b={G:b.G},b.G++){var g=e.filter(function(h){return function(m){return Eb(m,f[h.G].name)===f[h.G].value}}(b));if(0===g.length)return{A:[],u:e,C:{s:f[b.G]},D:{i:a.i,attributes:f.slice(0,b.G)}};e=g}if(a.name){b=e.filter(function(h){a:{var m=a.name;h=Qa(h);if("*"===m)throw new Sa("* is invalid as an accessible name. To match any accessible name omit it from the locator e.g. {button}.");
var q=m.split("*");if(h.startsWith(q[0])&&h.endsWith(q[q.length-1])){m=0;q=z(q);for(var u=q.next();!u.done;u=q.next()){u=u.value;m=h.indexOf(u,m);if(-1===m){h=!1;break a}m+=u.length}h=!0}else h=!1}return h});if(0===b.length)return{A:[],u:e,C:{name:a.name},D:{i:a.i,attributes:a.attributes}};e=b}$a(e);return{o:e}};function Sb(a,b){if(b&&!b.contains(a))throw Error("Can't generate locator for element that is not contained within the root element.");if(!b){a=a.ownerDocument;if(!a)throw Error("Can't generate locator for detached element");b=a.body}return b}
function Tb(a,b){var c;a=Ub(a,b);if(null===a)return null;for(var d=[a.node],e=a.element.parentElement;null!==e;)e=Ub(e,b),null!==e&&(Wa.includes(e.node.i)&&(console.warn("Element "+e.element+" has a role of "+(e.node.i+", so it has presentational children (https://www.w3.org/TR/wai-aria-practices/#children_presentational). However it also has descendant elements which would otherwise have semantics - matched by semantic locator ")+(new X(d,[])+". These presentational elements will be ignored while generating this semantic locator")),
d=[],a=e),d.unshift(e.node)),e=null!==(c=null===e||void 0===e?void 0:e.element.parentElement)&&void 0!==c?c:null;P(Vb(d,b).includes(a.element),"Cannot find element again with locator we just generated:\nNodes: "+(d+"\nElement: ")+(a.element.outerHTML+"\n"));return{X:d,element:a.element}}
function Wb(a,b,c){P(0!==a.length,"Trying to refine empty array of nodes");if(1>=a.length)var d=a;else{d=Vb(a,c);for(var e=[],f=0;f<a.length-1;f++){var g=e.concat(a.slice(f+1));Vb(g,c).length>d.length&&e.push(a[f])}e.push(a[a.length-1]);d=e}e=d;P(Vb(e,c).includes(b),"Removing redundant nodes does not resolve element anymore:\nInitial nodes: "+(a+"\nAfter refinement: ")+(e+"\n"));a=new X(e,[]);d=Xb(a,c);e=new X([],e);c=Xb(e,c);return c.includes(b)&&c.length<d.length?e:a}
function Ub(a,b){for(;null!==a&&b.contains(a)&&b!==a;){var c=cc(a);if(null!==c)return{node:c,element:a};a=a.parentElement}return null}function cc(a){if(ub(a))return null;var b=xb(a);return null===b?null:new Lb(b,[],Qa(a))}function Xb(a,b){b=Y(a,b);P(Fb(b),"Locator "+a+" didn't find any elements");return b.o}function Vb(a,b){a=new X(a,[]);return Xb(a,b)};function dc(a){return function(b){for(var c=[],d=0;d<arguments.length;++d)c[d-0]=arguments[d];try{return a.apply(null,ea(c))}catch(e){throw e instanceof K&&(e=Error(e.P+": "+e.message)),e;}}}function Z(a,b){"function"===typeof b&&(b=dc(b));window[a]=b}Z("findElementsBySemanticLocator",function(a,b){b=void 0===b?document.body:b;a=Y(Pb(a),b);return V(a)?[]:a.o});
Z("findElementBySemanticLocator",function(a,b){b=void 0===b?document.body:b;var c=Pb(a),d=Y(c,b);if(V(d)){a=Y(c,b,!0);a=V(a)?[]:a.o;b=Y(c,b,!1,!0);b=V(b)?[]:b.o;c="Didn't find any elements matching semantic locator "+c+". ";var e=d.u,f=d.D,g=d.C;d=d.A;var h=1<e.length;0===d.length?void 0===f?c+="No elements have "+W(g)+".":(c+=e.length+" element"+(h?"s":"")+" with "+(Gb(f)+" were found. "),c+="However "+(h?"none had":"it didn't have")+" "+(W(g)+". ")+(Hb(g,e)+".")):void 0===f?c+=e.length+" element"+
(h?"s":"")+" matched the locator "+(d.join(" ")+", but ")+((h?"none had":"it didn't have")+" a descendant with ")+(W(g)+"."):(c+=e.length+" descendant"+(h?"s":"")+" of "+(d.join(" ")+" with "+Gb(f)+" were found. "),c+="However "+(h?"none had":"it didn't have")+" "+(W(g)+". ")+(Hb(g,e)+"."));0<a.length&&(c+=" "+a.length+" hidden element"+((1<a.length?"s":"")+" matched the locator. To match these elements, ensure they're not hidden (aria-hidden is false and they're not hidden by css)."));0<b.length&&
(a=1<b.length,c+=" "+b.length+" element"+((a?"s":"")+" would have matched the locator, but ")+((a?"have":"it has")+" an ancestor with presentational children (https://www.w3.org/TR/wai-aria-practices/#children_presentational), erasing its semantics."));throw new Ra(c);}return d.o[0]});Z("closestPreciseLocatorFor",function(a,b){b=Sb(a,b);if(!b)return null;a=Tb(a,b);return null===a?null:Wb(a.X,a.element,b).toString()});
Z("preciseLocatorFor",function(a,b){b=Sb(a,b);if(!b)return null;var c=Tb(a,b);return null===c||c.element!==a?null:Wb(c.X,c.element,b).toString()});Z("closestSimpleLocatorFor",function(a,b){var c,d,e;return(b=Sb(a,b))?null!==(e=null===(d=null===(c=Ub(a,b))||void 0===c?void 0:c.node)||void 0===d?void 0:d.toString())&&void 0!==e?e:null:null});Z("simpleLocatorFor",function(a){var b,c;return null!==(c=null===(b=cc(a))||void 0===b?void 0:b.toString())&&void 0!==c?c:null});Z("semanticLocatorsReady",!0);}).call(this);
