(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ca=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");
},da=ca(this),w=function(a,b){if(b)a:{var c=da;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}};
w("Symbol",function(a){if(a)return a;var b=function(f,g){this.$=f;ba(this,"description",{configurable:!0,writable:!0,value:g})};b.prototype.toString=function(){return this.$};var c="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",d=0,e=function(f){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b(c+(f||"")+"_"+d++,f)};return e});
w("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=da[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ba(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ea(aa(this))}})}return a});
var ea=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a},y=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}},z=function(a){if(!(a instanceof Array)){a=y(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a},fa="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},ha;
if("function"==typeof Object.setPrototypeOf)ha=Object.setPrototypeOf;else{var ia;a:{var ja={a:!0},na={};try{na.__proto__=ja;ia=na.a;break a}catch(a){}ia=!1}ha=ia?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var oa=ha,A=function(a,b){a.prototype=fa(b.prototype);a.prototype.constructor=a;if(oa)oa(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.ka=b.prototype},pa=function(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b},B=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
w("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});w("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});
var qa=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};w("String.prototype.includes",function(a){return a?a:function(b,c){return-1!==qa(this,b,"includes").indexOf(b,c||0)}});
w("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(h){return h};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof f){b=f.call(b);for(var g=0;!(f=b.next()).done;)e.push(c.call(d,f.value,g++))}else for(f=b.length,g=0;g<f;g++)e.push(c.call(d,b[g],g));return e}});w("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)B(b,d)&&c.push([d,b[d]]);return c}});
w("WeakMap",function(a){function b(){}function c(m){var q=typeof m;return"object"===q&&null!==m||"function"===q}function d(m){if(!B(m,f)){var q=new b;ba(m,f,{value:q})}}function e(m){var q=Object[m];q&&(Object[m]=function(u){if(u instanceof b)return u;Object.isExtensible(u)&&d(u);return q(u)})}if(function(){if(!a||!Object.seal)return!1;try{var m=Object.seal({}),q=Object.seal({}),u=new a([[m,2],[q,3]]);if(2!=u.get(m)||3!=u.get(q))return!1;u.delete(m);u.set(q,4);return!u.has(m)&&4==u.get(q)}catch(F){return!1}}())return a;
var f="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var g=0,h=function(m){this.K=(g+=Math.random()+1).toString();if(m){m=y(m);for(var q;!(q=m.next()).done;)q=q.value,this.set(q[0],q[1])}};h.prototype.set=function(m,q){if(!c(m))throw Error("Invalid WeakMap key");d(m);if(!B(m,f))throw Error("WeakMap key fail: "+m);m[f][this.K]=q;return this};h.prototype.get=function(m){return c(m)&&B(m,f)?m[f][this.K]:void 0};h.prototype.has=function(m){return c(m)&&B(m,f)&&B(m[f],this.K)};
h.prototype.delete=function(m){return c(m)&&B(m,f)&&B(m[f],this.K)?delete m[f][this.K]:!1};return h});
w("Map",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var h=Object.seal({x:4}),m=new a(y([[h,"s"]]));if("s"!=m.get(h)||1!=m.size||m.get({x:4})||m.set({x:4},"t")!=m||2!=m.size)return!1;var q=m.entries(),u=q.next();if(u.done||u.value[0]!=h||"s"!=u.value[1])return!1;u=q.next();return u.done||4!=u.value[0].x||"t"!=u.value[1]||!q.next().done?!1:!0}catch(F){return!1}}())return a;var b=new WeakMap,c=function(h){this.J={};this.B=f();
this.size=0;if(h){h=y(h);for(var m;!(m=h.next()).done;)m=m.value,this.set(m[0],m[1])}};c.prototype.set=function(h,m){h=0===h?0:h;var q=d(this,h);q.list||(q.list=this.J[q.id]=[]);q.m?q.m.value=m:(q.m={next:this.B,F:this.B.F,head:this.B,key:h,value:m},q.list.push(q.m),this.B.F.next=q.m,this.B.F=q.m,this.size++);return this};c.prototype.delete=function(h){h=d(this,h);return h.m&&h.list?(h.list.splice(h.index,1),h.list.length||delete this.J[h.id],h.m.F.next=h.m.next,h.m.next.F=h.m.F,h.m.head=null,this.size--,
!0):!1};c.prototype.clear=function(){this.J={};this.B=this.B.F=f();this.size=0};c.prototype.has=function(h){return!!d(this,h).m};c.prototype.get=function(h){return(h=d(this,h).m)&&h.value};c.prototype.entries=function(){return e(this,function(h){return[h.key,h.value]})};c.prototype.keys=function(){return e(this,function(h){return h.key})};c.prototype.values=function(){return e(this,function(h){return h.value})};c.prototype.forEach=function(h,m){for(var q=this.entries(),u;!(u=q.next()).done;)u=u.value,
h.call(m,u[1],u[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(h,m){var q=m&&typeof m;"object"==q||"function"==q?b.has(m)?q=b.get(m):(q=""+ ++g,b.set(m,q)):q="p_"+m;var u=h.J[q];if(u&&B(h.J,q))for(h=0;h<u.length;h++){var F=u[h];if(m!==m&&F.key!==F.key||m===F.key)return{id:q,list:u,index:h,m:F}}return{id:q,list:u,index:-1,m:void 0}},e=function(h,m){var q=h.B;return ea(function(){if(q){for(;q.head!=h.B;)q=q.F;for(;q.next!=q.head;)return q=q.next,{done:!1,value:m(q)};q=null}return{done:!0,
value:void 0}})},f=function(){var h={};return h.F=h.next=h.head=h},g=0;return c});w("String.prototype.startsWith",function(a){return a?a:function(b,c){var d=qa(this,b,"startsWith");b+="";var e=d.length,f=b.length;c=Math.max(0,Math.min(c|0,d.length));for(var g=0;g<f&&c<e;)if(d[c++]!=b[g++])return!1;return g>=f}});
w("String.prototype.endsWith",function(a){return a?a:function(b,c){var d=qa(this,b,"endsWith");b+="";void 0===c&&(c=d.length);c=Math.max(0,Math.min(c|0,d.length));for(var e=b.length;0<e&&0<c;)if(d[--c]!=b[--e])return!1;return 0>=e}});var ra=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};
w("Array.prototype.values",function(a){return a?a:function(){return ra(this,function(b,c){return c})}});
w("Set",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),d=new a(y([c]));if(!d.has(c)||1!=d.size||d.add(c)!=d||1!=d.size||d.add({x:4})!=d||2!=d.size)return!1;var e=d.entries(),f=e.next();if(f.done||f.value[0]!=c||f.value[1]!=c)return!1;f=e.next();return f.done||f.value[0]==c||4!=f.value[0].x||f.value[1]!=f.value[0]?!1:e.next().done}catch(g){return!1}}())return a;var b=function(c){this.v=new Map;if(c){c=
y(c);for(var d;!(d=c.next()).done;)this.add(d.value)}this.size=this.v.size};b.prototype.add=function(c){c=0===c?0:c;this.v.set(c,c);this.size=this.v.size;return this};b.prototype.delete=function(c){c=this.v.delete(c);this.size=this.v.size;return c};b.prototype.clear=function(){this.v.clear();this.size=0};b.prototype.has=function(c){return this.v.has(c)};b.prototype.entries=function(){return this.v.entries()};b.prototype.values=function(){return this.v.values()};b.prototype.keys=b.prototype.values;
b.prototype[Symbol.iterator]=b.prototype.values;b.prototype.forEach=function(c,d){var e=this;this.v.forEach(function(f){return c.call(d,f,f,e)})};return b});w("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,f=0;f<e;f++){var g=d[f];if(b.call(c,g,f,d)){b=g;break a}}b=void 0}return b}});
w("Array.prototype.flatMap",function(a){return a?a:function(b,c){for(var d=[],e=0;e<this.length;e++){var f=b.call(c,this[e],e,this);Array.isArray(f)?d.push.apply(d,f):d.push(f)}return d}});/*

 Copyright 2020 Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
function sa(){return{h:{Z:[],M:[]}}};function ta(a){var b;return{X:null!==(b=a.X)&&void 0!==b?b:!1}};function ua(a,b){var c,d,e,f;return null!==(f=null!==(d=null===(c=a.matches)||void 0===c?void 0:c.call(a,b))&&void 0!==d?d:null===(e=a.msMatchesSelector)||void 0===e?void 0:e.call(a,b))&&void 0!==f?f:a.webkitMatchesSelector(b)}function va(a,b){if(a.closest)return a.closest(b);for(;!ua(a,b);){if(null===a.parentElement)return null;a=a.parentElement}return a};function E(a){return a.nodeType===Node.ELEMENT_NODE&&"http://www.w3.org/1999/xhtml"===a.namespaceURI}function wa(a){return a.nodeType===Node.ELEMENT_NODE&&"http://www.w3.org/2000/svg"===a.namespaceURI}function G(a,b){return a.tagName.toLowerCase()===b};function xa(a){if(!E(a))return!1;if("hidden"===window.getComputedStyle(a).visibility||null!==va(a,'[hidden],[aria-hidden="true"]'))return!0;for(;null!==a;){if("none"===window.getComputedStyle(a).display)return!0;a=a.parentElement}return!1};function za(a){var b,c,d=null!==(c=null===(b=a.getAttribute("aria-labelledby"))||void 0===b?void 0:b.split(" "))&&void 0!==c?c:[];a=[];d=y(d);for(var e=d.next();!e.done;e=d.next())(e=document.getElementById(e.value))&&a.push(e);return a};var Aa=["email","tel","text","url","search"],Ba=["number","range"],Ca=["spinbutton","slider","progressbar","scrollbar"];
function Da(a){var b,c=null!==(b=a.getAttribute("role"))&&void 0!==b?b:"",d=Ca.includes(c);if(c&&!d)return null;c=G(a,"input")&&Ba.includes(a.type)||G(a,"progress");if(d||c){if(a.hasAttribute("aria-valuetext"))return a.getAttribute("aria-valuetext");if(a.hasAttribute("aria-valuenow"))return a.getAttribute("aria-valuenow");if(G(a,"input"))return a.value;if(G(a,"progress"))return a.value.toString()}return null}
function Ea(a,b,c,d){var e=a.getAttribute("role");if(e&&"listbox"!==e&&"combobox"!==e)return null;if(G(a,"input")&&Aa.includes(a.type)&&(a.hasAttribute("list")||"combobox"===e))return a.value;var f=[];e&&"listbox"===e?f=Array.from(a.querySelectorAll('[role="option"][aria-selected="true"]')):G(a,"select")&&(f=Array.from(a.selectedOptions));return 0<f.length?f.map(function(g){return d(g,b,{h:c.h}).name}).filter(function(g){return""!==g}).join(" "):null}
function Fa(a,b,c,d){if(!E(a)||!c.h.I)return null;var e;return(e=(e=a.getAttribute("role"))&&"textbox"!==e?null:G(a,"textarea")||G(a,"input")&&Aa.includes(a.type)&&!a.hasAttribute("list")?a.value:null)?e:(b=Ea(a,b,c,d))?b:(a=Da(a))?a:null};var Ga="BUTTON INPUT METER OUTPUT PROGRESS SELECT TEXTAREA".split(" ");function Ha(a,b,c,d){return Array.from(document.querySelectorAll("label")).filter(function(e){return void 0!==e.control?e.control===a:""!==e.htmlFor&&e.htmlFor===a.id?!0:""===e.htmlFor&&e.contains(a)?!0:!1}).map(function(e){return d(e,b,{O:!0,h:c.h}).name}).filter(function(e){return""!==e}).join(" ")||null};var Ia={T:"button cell checkbox columnheader gridcell heading link menuitem menuitemcheckbox menuitemradio option radio row rowgroup rowheader switch tab tooltip tree treeitem".split(" "),tags:"button h1 h2 h3 h4 h5 h6 summary tbody tfoot thead".split(" ")},Ja={T:"alert alertdialog application article banner complementary dialog document feed figure form grid group img listbox log main marquee math menu menubar navigation radiogroup region scrollbar search searchbox separator slider spinbutton tablist tabpanel textbox timer toolbar treegrid".split(" "),
tags:"article aside body datalist dialog fieldset figure footer form header hr img input main math menu nav optgroup section select textarea".split(" ")},Ka={T:"contentinfo definition directory list note status table term".split(" "),tags:"dd details dl ol output table ul".split(" ")};
function La(a){switch(a){case "th":return function(b){return null!==va(b,"table")};case "td":return function(b){return null!==va(b,"table")};case "option":return function(b){return null!==va(b,"select,datalist")};case "a":return function(b){return b.hasAttribute("href")};case "area":return function(b){return b.hasAttribute("href")};case "link":return function(b){return b.hasAttribute("href")};default:return null}}
function Ma(a,b){var c,d,e=null!==(d=null===(c=a.getAttribute("role"))||void 0===c?void 0:c.trim().toLowerCase())&&void 0!==d?d:"";return b.T.includes(e)||b.tags.includes(a.nodeName.toLowerCase())?!0:!1}
function Na(a,b){var c;if(b.h.I&&a.parentElement&&Ma(a.parentElement,Ia)&&Ma(a,Ka))return!0;if(Ma(a,Ja))return"menu"===(null===(c=a.getAttribute("role"))||void 0===c?void 0:c.toLowerCase())?!1:(G(a,"a")||G(a,"area")||G(a,"link"))&&a.hasAttribute("href")||(G(a,"input")||G(a,"select")||G(a,"textarea")||G(a,"button"))&&!a.hasAttribute("disabled")?!0:a.hasAttribute("tabindex")||a.isContentEditable;if(Ma(a,Ia))return!0;var d=La(a.nodeName.toLowerCase());return d&&d(a)||b.O||b.h.I?!0:!1}
function Oa(a,b){b=window.getComputedStyle(a,b);a=b.content;b="block"===b.display;return'"'===a[0]&&'"'===a[a.length-1]||"'"===a[0]&&"'"===a[a.length-1]?b?" "+a.slice(1,-1)+" ":a.slice(1,-1):""}var Pa="a abbr acronym b bdi bdo big button canvas cite code data datalist del dfn em embed i iframe img ins kbd label map mark meter noscript object output picture progress q ruby s samp script select slot small span strong sub sup template textarea time tt u var video wbr".split(" ");var Qa="text password search tel email url".split(" ");var Ra={"2A":function(a,b,c){b=null;xa(a)&&!c.O&&(b="");return b},"2B":function(a,b,c,d){if(!E(a)||c.O)return null;a=za(a);return 0===a.length?null:a.map(function(e){c.h.I=!0;return d(e,b,{O:!0,h:c.h}).name}).join(" ").trim()},"2C":function(a,b,c,d){var e;if(a.nodeType!==Node.ELEMENT_NODE)return null;var f=null!==(e=a.getAttribute("aria-label"))&&void 0!==e?e:"";return""===f.trim()?null:c.h.I&&(a=Fa(a,b,{h:c.h},d),null!==a)?a:f},"2D":function(a,b,c,d){if(wa(a))for(var e=y(a.childNodes),f=e.next();!f.done;f=
e.next())if(f=f.value,wa(f)&&G(f,"title"))return f.textContent;(e=!E(a))||(e=a.getAttribute("role"),e="presentation"===e||"none"===e||null===e&&G(a,"img")&&""===a.getAttribute("alt")?!0:!1);if(e)return null;if(Ga.includes(a.tagName)&&(e=Ha(a,b,c,d)))return e;if(G(a,"input")){var g;e=null!==(g=a.getAttribute("type"))&&void 0!==g?g:"";if(g="button"!==e&&"submit"!==e&&"reset"!==e||!a.hasAttribute("value")?"submit"===e||"reset"===e?e:"image"===e&&a.hasAttribute("alt")?a.getAttribute("alt"):"image"!==
e||a.hasAttribute("title")?null:"Submit Query":a.value)return g}return G(a,"table")&&(g=a.querySelector("caption"))?(c.h.I=!0,d(g,b,{h:c.h}).name):G(a,"figure")&&(g=a.querySelector("figcaption"))?(c.h.I=!0,d(g,b,{h:c.h}).name):G(a,"fieldset")&&(g=a.querySelector("legend"))?(c.h.I=!0,d(g,b,{h:c.h}).name):(b=a.getAttribute("alt"))&&(G(a,"img")||G(a,"area"))?b:null},"2E":Fa,"2F":function(a,b,c,d){if(!E(a)||!Na(a,c))return null;var e=Array.from(a.childNodes),f=a.getAttribute("aria-owns");if(f){f=y(f.split(" "));
for(var g=f.next();!g.done;g=f.next())(g=document.getElementById(g.value))&&e.push(g)}f=[];e=y(e);for(g=e.next();!g.done;g=e.next())if(g=g.value,!c.h.Z.includes(g)){c.h.Z.push(g);c.h.I=!0;var h=d(g,b,{h:c.h}).name;Pa.includes(g.nodeName.toLowerCase())||g.nodeType===Node.TEXT_NODE?f.push(h):f.push(" "+h+" ")}b.X&&(f.unshift(Oa(a,":before")),f.push(Oa(a,":after")));a=f.join("");return""===a.trim()?null:a},"2G":function(a){return a.nodeType===Node.TEXT_NODE?a.data:null},"2I":function(a){return E(a)?
a.title?a.title:G(a,"input")&&Qa.includes(a.type)?a.placeholder:G(a,"textarea")&&a.hasAttribute("placeholder")?a.getAttribute("placeholder"):null:null}};function Sa(a,b,c){b=void 0===b?ta({}):b;c=void 0===c?sa():c;for(var d=y(Object.entries(Ra)),e=d.next();!e.done;e=d.next()){var f=y(e.value);e=f.next().value;f=f.next().value;f=f(a,b,c,Sa);if(null!==f)return b=f.replace(/\s+/g," "),c.h.M.push({ja:e,node:a,text:b}),{name:b,M:c.h.M}}return{name:"",M:c.h.M}};/*

 Copyright 2021 The Semantic Locators Authors
 SPDX-License-Identifier: Apache-2.0
*/
function Ta(a){throw Error("unexpected value "+a+"!");}function Ua(a){if(Va())for(var b=1;b<a.length;b++)if(0<I(a[b-1],a[b]))throw Error("Elements not passed in document order. Index "+(b-1)+" comes after index "+(b+". Elements: "+JSON.stringify(a)));}function I(a,b){return a===b?0:a.compareDocumentPosition(b)&Node.DOCUMENT_POSITION_PRECEDING?1:-1}function Wa(a){return a.filter(function(b,c){return a[c-1]!==b})}function J(a,b){return a.tagName.toLowerCase()===b}
function K(a,b){if(Va()&&!a)throw a="Assertion failed",void 0!==b&&(a+=": "+b),Error(a);}function Xa(a,b){if(Va()&&!a)throw Error("Assertion failed: "+b());}function Va(){var a,b;return(null===(b=null===(a=window)||void 0===a?void 0:a.ia)||void 0===b?void 0:b.ga)||!1};var Ya=[],L=!1;function Za(a){K(!L,"Already in a batch operation");L=!0;try{a()}finally{K(L,"Not in a batch operation");L=!1;a=y(Ya);for(var b=a.next();!b.done;b=a.next())b.value.clear()}}function $a(a){var b=new Map;Ya.push(b);return function(){var c=pa.apply(0,arguments);if(!L)return a.apply(null,z(c));for(var d=b,e=y(c),f=e.next();!f.done;f=e.next())f=f.value,f=void 0!==f.W?f.W():f,d=ab(d,f,function(){return new Map});return ab(d,void 0,function(){return a.apply(null,z(c))})}}
function ab(a,b,c){var d=a.get(b);void 0===d&&(d=c(),a.set(b,d));return d};var M=function(){var a=Error.apply(this,arguments);this.message=a.message;"stack"in a&&(this.stack=a.stack);this.P="SemanticLocatorError"};A(M,Error);var bb=function(){M.apply(this,arguments);this.P="NoSuchElementError"};A(bb,M);var cb=function(){M.apply(this,arguments);this.P="ValueError"};A(cb,M);var N=function(){M.apply(this,arguments);this.P="InvalidLocatorError"};A(N,M);var db=$a(function(a){var b=void 0===b?{}:b;b=void 0===b?{}:b;var c=void 0===c?sa():c;return Sa(a,ta(b),c).name.trim()});var eb="checked current disabled pressed selected colindex level posinset readonly rowindex".split(" ");var fb=new Set("alert alertdialog application directory feed grid log marquee menu menubar menuitem menuitemcheckbox menuitemradio note radiogroup scrollbar search switch tab tablist tabpanel timer toolbar tooltip tree treegrid treeitem".split(" ")),gb="button checkbox img math menuitemcheckbox menuitemradio progressbar radio scrollbar separator slider switch tab".split(" "),O={article:{g:"article"},banner:{l:[{j:"header",conditions:[{type:1,V:'article,aside,main,nav,section,[role="article"],[role="complementary"],[role="main"],[role="navigation"],[role="region"]'}]}]},
button:{g:"button,summary",l:[{j:"input",conditions:[{type:5,propertyName:"type",values:["button","image","reset","submit"]}]}]},cell:{l:[{j:"td",conditions:[{type:6,tag:"table",i:"table"}]},{j:'th:not([scope="col"]):not([scope="colgroup"]):not([scope="row"]):not([scope="rowgroup"])',conditions:[{type:6,tag:"table",i:"table"},{type:8,S:!0},{type:7,N:!0}]}]},checkbox:{l:[{j:"input",conditions:[{type:5,propertyName:"type",values:["checkbox"]}]}]},columnheader:{g:'th[scope="col"],th[scope="colgroup"]',
l:[{j:'th:not([scope="col"]):not([scope="colgroup"]):not([scope="row"]):not([scope="rowgroup"])',conditions:[{type:7,N:!1}]}]},combobox:{g:"select:not([multiple]):not([size])",l:[{j:"select:not([multiple])",conditions:[{type:3,s:"size",value:2}]},{j:"input[list]",conditions:[{type:5,propertyName:"type",values:["email","search","tel","text","url"]}]}]},complementary:{g:"aside"},contentinfo:{l:[{j:"footer",conditions:[{type:1,V:'article,aside,main,nav,section,[role="article"],[role="complementary"],[role="main"],[role="navigation"],[role="region"]'}]}]},
definition:{g:"dd"},dialog:{g:"dialog"},document:{g:"body"},figure:{g:"figure"},form:{l:[{j:"form",conditions:[{type:4}]}]},gridcell:{l:[{j:"td",conditions:[{type:6,tag:"table",i:"grid"}]},{j:"td",conditions:[{type:6,tag:"table",i:"treegrid"}]},{j:'th:not([scope="col"]):not([scope="colgroup"]):not([scope="row"]):not([scope="rowgroup"])',conditions:[{type:6,tag:"table",i:"treegrid"},{type:8,S:!0},{type:7,N:!0}]}]},group:{g:"details,fieldset,optgroup"},heading:{g:"h1,h2,h3,h4,h5,h6"},img:{g:'img:not([alt]),img[alt]:not([alt=""])'},
link:{g:"a[href],area[href],link[href]"},list:{g:"menu,ol,ul"},listbox:{g:"datalist,select[multiple]",l:[{j:"select",conditions:[{type:2,s:"size",value:1}]}]},listitem:{g:"li"},main:{g:"main"},math:{g:"math"},navigation:{g:"nav"},option:{g:"datalist > option,select > optgroup > option,select > option"},progressbar:{g:"progress"},radio:{l:[{j:"input",conditions:[{type:5,propertyName:"type",values:["radio"]}]}]},region:{l:[{j:"section",conditions:[{type:4}]}]},row:{g:"tr"},rowgroup:{g:"tbody,tfoot,thead"},
rowheader:{g:'th[scope="row"],th[scope="rowgroup"]',l:[{j:'th:not([scope="col"]):not([scope="colgroup"]):not([scope="row"]):not([scope="rowgroup"])',conditions:[{type:8,S:!1},{type:7,N:!0}]}]},searchbox:{l:[{j:"input:not([list])",conditions:[{type:5,propertyName:"type",values:["search"]}]}]},separator:{g:"hr"},slider:{l:[{j:"input",conditions:[{type:5,propertyName:"type",values:["range"]}]}]},spinbutton:{l:[{j:"input",conditions:[{type:5,propertyName:"type",values:["number"]}]}]},status:{g:"output"},
table:{g:"table"},term:{g:"dfn,dt"},textbox:{g:"textarea",l:[{j:"input:not([list])",conditions:[{type:5,propertyName:"type",values:["email","tel","text","url"]}]}]}},hb={a:["link"],area:["link"],article:["article"],aside:["complementary"],body:["document"],button:["button"],datalist:["listbox"],dd:["definition"],details:["group"],dfn:["term"],dialog:["dialog"],dt:["term"],fieldset:["group"],figure:["figure"],footer:["contentinfo"],form:["form"],h1:["heading"],h2:["heading"],h3:["heading"],h4:["heading"],
h5:["heading"],h6:["heading"],header:["banner"],hr:["separator"],img:["img"],input:"button checkbox combobox radio searchbox slider spinbutton textbox".split(" "),li:["listitem"],link:["link"],main:["main"],math:["math"],menu:["list"],nav:["navigation"],ol:["list"],optgroup:["group"],option:["option"],output:["status"],progress:["progressbar"],section:["region"],select:["combobox","listbox"],summary:["button"],table:["table"],tbody:["rowgroup"],td:["cell","gridcell"],textarea:["textbox"],tfoot:["rowgroup"],
th:["cell","columnheader","gridcell","rowheader"],thead:["rowgroup"],tr:["row"],ul:["list"]},ib=["none","presentation"];function jb(a,b){a=kb(a);b=vb(a,b);return a.cells.slice(b.ea,b.ca+1).some(function(c){return c.some(P)})}function wb(a,b){a=kb(a);b=vb(a,b);var c=b.da,d=b.ba;return a.cells.some(function(e){return e.slice(c,d+1).some(P)})}
var xb=function(a){this.cells=a=void 0===a?[]:a},yb=function(a,b,c){return Q(a,c)[b]},Q=function(a,b){void 0===a.cells[b]&&(a.cells[b]=[]);return a.cells[b]},vb=function(a,b){for(var c=a.width,d=a.height,e=-1,f=-1,g=0;g<a.height;g++){var h=Q(a,g),m=h.indexOf(b);-1!==m&&(e=Math.max(e,h.lastIndexOf(b)),f=Math.max(f,g),c=Math.min(c,m),d=Math.min(d,g))}K(e<a.width&&f<a.height&&-1<c&&-1<d,"Target cell not found in table");return{da:c,ea:d,ba:e,ca:f}};xb.prototype.concat=function(a){this.cells=this.cells.concat(a.cells)};
da.Object.defineProperties(xb.prototype,{height:{configurable:!0,enumerable:!0,get:function(){return this.cells.length}},width:{configurable:!0,enumerable:!0,get:function(){return Math.max.apply(Math,z(this.cells.map(function(a){return a.length})))}}});
function kb(a){var b=new xb;null!==a.tHead&&b.concat(zb(a.tHead.rows));for(var c=y(a.tBodies),d=c.next();!d.done;d=c.next())b.concat(zb(d.value.rows));c=[];d=y(a.children);for(var e=d.next();!e.done;e=d.next())e=e.value,e.nodeType===Node.ELEMENT_NODE&&"http://www.w3.org/1999/xhtml"===e.namespaceURI&&J(e,"tr")&&c.push(e);b.concat(zb(c));null!==a.tFoot&&b.concat(zb(a.tFoot.rows));return b}
function zb(a){for(var b=new xb,c=[],d=0;d<a.length;d++){for(var e=0,f=y(a[d].cells),g=f.next();!g.done;g=f.next()){for(g=g.value;yb(b,e,d)||c[e];){if(!P(yb(b,e,d))&&c[e]){var h=e,m=c[e];Q(b,d)[h]=m}e++}for(h=e;h<e+g.colSpan;h++)for(0===Ab(g)&&(c[h]=g,m=h,Q(b,d)[m]=g),m=d;m<d+Ab(g);m++)if(!P(yb(b,h,m))){var q=h;Q(b,m)[q]=g}e+=g.colSpan}for(;e<b.width;e++)f=c[e],void 0===f||P(yb(b,e,d))||(g=e,Q(b,d)[g]=f)}return b}
function Ab(a){a=a.getAttribute("rowSpan");if(null===a||""===a.trim())return 1;a=Number(a);return isNaN(a)?1:a}function P(a){return void 0!==a&&J(a,"td")};function Bb(a,b,c,d){var e,f=Array.from(b.querySelectorAll('[role="'+a+'"]'));if(fb.has(a))return f.filter(function(m){return c||!Cb(m)}).filter(function(m){return d||null===(m.parentElement?R(m.parentElement,Db):null)});f=new Set(f);a=O[a];var g=a.g;if(g){g=Eb(g,b);var h=y(g);for(g=h.next();!g.done;g=h.next())f.add(g.value)}a=y(null!==(e=a.l)&&void 0!==e?e:[]);for(g=a.next();!g.done;g=a.next())for(g=g.value,g=Eb(g.j,b,g.conditions),h=y(g),g=h.next();!g.done;g=h.next())f.add(g.value);return Fb(f).filter(function(m){return c||
!Cb(m)}).filter(function(m){return d||null===(m.parentElement?R(m.parentElement,Db):null)}).sort(I)}function S(a){var b,c=a.getAttribute("role");return null!==c?ib.includes(c)||!fb.has(c)&&!O.hasOwnProperty(c)?null:c:(null!==(b=hb[a.tagName.toLowerCase()])&&void 0!==b?b:[]).find(function(d){return Gb(a,d)})||null}
function Cb(a){if("hidden"===window.getComputedStyle(a).visibility||null!==R(a,'[aria-hidden="true"]'))return!0;for(;null!==a;){if("none"===window.getComputedStyle(a).display)return!0;a=a.parentElement}return!1}
function Hb(a,b){switch(b.type){case 2:var c=a.getAttribute(b.s);return null!==c&&Number(c)>b.value;case 3:return c=a.getAttribute(b.s),null!==c&&Number(c)<b.value;case 4:return a.hasAttribute("aria-label")||a.hasAttribute("aria-labelledby")&&a.getAttribute("aria-labelledby").split(" ").some(function(d){return void 0!==document.getElementById(d)});case 1:return null===R(a,b.V);case 0:return a[b.propertyName]===b.value;case 5:return b.values.some(function(d){return d===a[b.propertyName]});case 6:c=
a.parentElement;if(null===c)return!1;c=R(c,b.tag);return null!==c&&S(c)===b.i;case 8:return c=R(a,"table"),null===c?!1:b.S===wb(c,a);case 7:return c=R(a,"table"),null===c?!1:b.N===jb(c,a);default:Ta(b)}}function Ib(a,b,c){var d=R(a.parentElement,Jb(b));return null===d?null:c.flatMap(function(e){return Bb(e,d,!1,!1)}).filter(function(e){return d===R(e.parentElement,Jb(b))}).sort(I).indexOf(a)+1||null}
function Gb(a,b){var c,d;b=O[b];var e=b.g;return e&&Kb(a,e)?!0:null!==(d=null===(c=b.l)||void 0===c?void 0:c.some(function(f){return Kb(a,f.j)&&f.conditions.every(function(g){return Hb(a,g)})}))&&void 0!==d?d:!1}var Db=gb.map(Jb).join(",");
function Jb(a){var b,c='[role="'+a+'"]';if(O.hasOwnProperty(a)){var d=O[a];void 0!==d.g&&(c+=","+Lb(d.g));for(var e=y(null!==(b=d.l)&&void 0!==b?b:[]),f=e.next();!f.done;f=e.next())if("input"!==f.value.j)throw Error("Not implemented: closestWithRole called with a role which requires a condition to be checked. Role: "+a+"; Selector: "+d);}return c}function Eb(a,b,c){a=Array.from(b.querySelectorAll(Lb(a)));return c?a.filter(function(d){return c.every(function(e){return Hb(d,e)})}):a}
function Lb(a){return a.split(",").map(function(b){return b+":not([role])"}).join(",")}function Kb(a,b){var c,d,e,f;return null!==(f=null!==(d=null===(c=a.matches)||void 0===c?void 0:c.call(a,b))&&void 0!==d?d:null===(e=a.msMatchesSelector)||void 0===e?void 0:e.call(a,b))&&void 0!==f?f:a.webkitMatchesSelector(b)}function R(a,b){if(a.closest)return a.closest(b);for(;!Kb(a,b);){if(null===a.parentElement)return null;a=a.parentElement}return a}
function Fb(a){var b=[];a=y(a);for(var c=a.next();!c.done;c=a.next())b.push(c.value);return b};function Mb(a,b){if(a.hasAttribute("aria-"+b))return a.getAttribute("aria-"+b);switch(b){case "checked":return J(a,"input")&&["checkbox","radio"].includes(a.type)?a.checked.toString():null;case "current":return"false";case "disabled":return((J(a,"button")||J(a,"fieldset")||J(a,"input")||J(a,"optgroup")||J(a,"option")||J(a,"select")||J(a,"textarea"))&&a.disabled).toString();case "pressed":return"false";case "selected":return J(a,"option")?a.selected.toString():null;case "colindex":return(a=Ib(a,"row",
["columnheader","cell"]))?String(a):null;case "level":return a=a.tagName.match(/^H([1-6])$/),null===a?null:a[1];case "rowindex":return(a=Ib(a,"table",["row"]))?String(a):null;case "posinset":return b=S(a),"listitem"===b?(a=Ib(a,"list",["listitem"]))?String(a):null:"treeitem"===b?(a=Ib(a,"tree",["treeitem"]))?String(a):null:null;case "readonly":return(J(a,"input")&&a.readOnly||"false"===a.contentEditable).toString();default:Ta(b)}};function T(a){return void 0!==a.u}function Nb(a){return void 0!==a.o}function U(a){return void 0!==a.i?"an ARIA role of "+a.i:void 0!==a.s?"aria-"+a.s.name+" = "+a.s.value:'an accessible name of "'+a.name+'"'}function Ob(a){var b,c=[];a.i&&c.push(U({i:a.i}));a.attributes&&(c=c.concat(a.attributes.map(function(d){return U({s:d})})));a.name&&c.push(U({name:a.name}));return 1>=c.length?null!==(b=c[0])&&void 0!==b?b:"":c.slice(0,c.length-1).join(", ")+(", and "+c[c.length-1])}
function Pb(a,b){if(void 0!==a.i)return b=b.map(function(c){return S(c)}).filter(function(c){return null!=c}),"Roles found: "+JSON.stringify(Array.from(new Set(b)));if(void 0!==a.s)return b=b.map(function(c){return Mb(c,a.s.name)}),"Values found for aria-"+a.s.name+": "+JSON.stringify(Array.from(new Set(b)));b=b.map(db).filter(function(c){return""!==c});return 0===b.length?"No matching elements had an accessible name":"Accessible names found: "+JSON.stringify(Array.from(new Set(b)))}
function Qb(a){var b=a.map(Rb),c=Math.max.apply(Math,z(b));a=a.filter(function(d,e){return b[e]===c});return{u:Wa(a.flatMap(function(d){return d.u}).sort(I)),A:a[0].A,D:a[0].D,C:a[0].C}}function Rb(a){var b,c=a.A.length;a=null!==(b=a.D)&&void 0!==b?b:{};var d=0;void 0!==a.i&&d++;void 0!==a.attributes&&(d+=a.attributes.length);void 0!==a.name&&d++;return c+d/50};function Sb(a){Ua(a);if(0===a.length)return[];var b=[a[0]];a=y(a);for(var c=a.next();!c.done;c=a.next())c=c.value,b[b.length-1].contains(c)||b.push(c);return b};var V=function(a,b){this.R=a;this.L=b;a=a.concat(b);b=y(a);for(var c=b.next();!c.done;c=b.next()){c=c.value;var d=c.i;if(!fb.has(d)&&!O.hasOwnProperty(d))throw new N("Invalid locator: "+this+(" Unknown role: "+c.i+". The list of valid roles can be found at https://www.w3.org/TR/wai-aria/#role_definitions"));if(c!==a[a.length-1]&&gb.includes(c.i))throw new N("Invalid locator: "+this+(' The role "'+c.i+'" has presentational children. That means its descendants cannot have semantics, so an element with a role of ')+
(c.i+" may only be the final element of a Semantic Locator. https://www.w3.org/TR/wai-aria-practices/#children_presentational"));c=y(c.attributes);for(d=c.next();!d.done;d=c.next())if(d=d.value,!eb.includes(d.name))throw new N("Invalid locator: "+this+(" Unsupported attribute: "+d.name+". Supported attributes: ")+eb);}};
V.prototype.toString=function(){for(var a=[],b=y(this.R),c=b.next();!c.done;c=b.next())a.push(c.value.toString());if(0<this.L.length)for(a.push("outer"),b=y(this.L),c=b.next();!c.done;c=b.next())a.push(c.value.toString());return a.join(" ")};V.prototype.W=function(){return this.toString()};var Tb=function(a,b,c){this.i=a;this.attributes=b;this.name=c};
Tb.prototype.toString=function(){var a="{"+this.i;if(this.name){a+=" ";var b=this.name;b=b.includes("'")&&!b.includes('"')?JSON.stringify(b):"'"+b.replace(/'/g,"\\'")+"'";a+=b}b=y(this.attributes);for(var c=b.next();!c.done;c=b.next())c=c.value,a+=" "+c.name+":"+c.value;return a+"}"};var Ub=function(a,b,c,d){b=Error.call(this);this.message=b.message;"stack"in b&&(this.stack=b.stack);this.message=a;this.o=c;this.location=d;this.name="SyntaxError";"function"===typeof Error.captureStackTrace&&Error.captureStackTrace(this,Ub)};A(Ub,Error);
var Vb=function(a,b){function c(g){return g.charCodeAt(0).toString(16).toUpperCase()}function d(g){return g.replace(/\\/g,"\\\\").replace(/"/g,'\\"').replace(/\0/g,"\\0").replace(/\t/g,"\\t").replace(/\n/g,"\\n").replace(/\r/g,"\\r").replace(/[\x00-\x0F]/g,function(h){return"\\x0"+c(h)}).replace(/[\x10-\x1F\x7F-\x9F]/g,function(h){return"\\x"+c(h)})}function e(g){return g.replace(/\\/g,"\\\\").replace(/\]/g,"\\]").replace(/\^/g,"\\^").replace(/-/g,"\\-").replace(/\0/g,"\\0").replace(/\t/g,"\\t").replace(/\n/g,
"\\n").replace(/\r/g,"\\r").replace(/[\x00-\x0F]/g,function(h){return"\\x0"+c(h)}).replace(/[\x10-\x1F\x7F-\x9F]/g,function(h){return"\\x"+c(h)})}function f(g){switch(g.type){case "literal":return'"'+d(g.text)+'"';case "class":var h=g.fa.map(function(m){return Array.isArray(m)?e(m[0])+"-"+e(m[1]):e(m)});return"["+(g.aa?"^":"")+h+"]";case "any":return"any character";case "end":return"end of input";case "other":return g.description}}return"Expected "+function(g){g=g.map(f);var h,m;g.sort();if(0<g.length){for(m=
h=1;h<g.length;h++)g[h-1]!==g[h]&&(g[m]=g[h],m++);g.length=m}switch(g.length){case 1:return g[0];case 2:return g[0]+" or "+g[1];default:return g.slice(0,-1).join(", ")+", or "+g[g.length-1]}}(a)+" but "+(b?'"'+d(b)+'"':"end of input")+" found."};
function Wb(a){function b(l,p){return{type:"literal",text:l,ignoreCase:p}}function c(l,p,r){return{type:"class",fa:l,aa:p,ignoreCase:r}}function d(l){var p=ka[l],r;if(!p){for(r=l-1;!ka[r];)r--;p=ka[r];for(p={line:p.line,H:p.H};r<l;)10===a.charCodeAt(r)?(p.line++,p.H=1):p.H++,r++;ka[l]=p}return p}function e(l,p){var r=d(l),t=d(p);return{start:{offset:l,line:r.line,H:r.H},end:{offset:p,line:t.line,H:t.H}}}function f(l){n<C||(n>C&&(C=n,ya=[]),ya.push(l))}function g(){var l;var p=n;var r=[];for(l=h();l!==
k;)r.push(l),l=h();if(r!==k){l=n;if("outer"===a.substr(n,5)){var t="outer";n+=5}else t=k,0===v&&f(gc);t===k&&(t=null);if(t!==k)if(t=H(),t!==k){t=[];var x=h();if(x!==k)for(;x!==k;)t.push(x),x=h();else t=k;t!==k?l=t:(n=l,l=k)}else n=l,l=k;else n=l,l=k;l===k&&(l=null);l!==k?(p=l||[],p=r=new V(r,p)):(n=p,p=k)}else n=p,p=k;return p}function h(){var l;var p=n;if(123===a.charCodeAt(n)){var r="{";n++}else r=k,0===v&&f(hc);if(r!==k)if(r=H(),r!==k)if(r=q(),r!==k){var t=H();if(t!==k){t=n;if(34===a.charCodeAt(n)){var x=
'"';n++}else x=k,0===v&&f(la);if(x!==k){x=[];for(l=u();l!==k;)x.push(l),l=u();x!==k?(34===a.charCodeAt(n)?(l='"',n++):(l=k,0===v&&f(la)),l!==k?t=x=x.join(""):(n=t,t=k)):(n=t,t=k)}else n=t,t=k;if(t===k)if(t=n,39===a.charCodeAt(n)?(x="'",n++):(x=k,0===v&&f(ma)),x!==k){x=[];for(l=F();l!==k;)x.push(l),l=F();x!==k?(39===a.charCodeAt(n)?(l="'",n++):(l=k,0===v&&f(ma)),l!==k?t=x=x.join(""):(n=t,t=k)):(n=t,t=k)}else n=t,t=k;t===k&&(t=null);if(t!==k)if(x=H(),x!==k){x=[];for(l=m();l!==k;)x.push(l),l=m();x!==
k?(l=H(),l!==k?(125===a.charCodeAt(n)?(l="}",n++):(l=k,0===v&&f(ic)),l!==k?(l=H(),l!==k?p=r=t?new Tb(r,x,t):new Tb(r,x):(n=p,p=k)):(n=p,p=k)):(n=p,p=k)):(n=p,p=k)}else n=p,p=k;else n=p,p=k}else n=p,p=k}else n=p,p=k;else n=p,p=k;else n=p,p=k;return p}function m(){var l=n;var p=H();if(p!==k)if(p=q(),p!==k){if(58===a.charCodeAt(n)){var r=":";n++}else r=k,0===v&&f(jc);if(r!==k){r=[];if(lb.test(a.charAt(n))){var t=a.charAt(n);n++}else t=k,0===v&&f(mb);if(t!==k)for(;t!==k;)r.push(t),lb.test(a.charAt(n))?
(t=a.charAt(n),n++):(t=k,0===v&&f(mb));else r=k;r!==k&&(r=r.join(""));r!==k?(t=H(),t!==k?l=p={name:p,value:r}:(n=l,l=k)):(n=l,l=k)}else n=l,l=k}else n=l,l=k;else n=l,l=k;return l}function q(){var l=[];if(nb.test(a.charAt(n))){var p=a.charAt(n);n++}else p=k,0===v&&f(ob);if(p!==k)for(;p!==k;)l.push(p),nb.test(a.charAt(n))?(p=a.charAt(n),n++):(p=k,0===v&&f(ob));else l=k;l!==k&&(l=l.join(""));return l}function u(){var l;var p=l=n;v++;if(34===a.charCodeAt(n)){var r='"';n++}else r=k,0===v&&f(la);r===k&&
(92===a.charCodeAt(n)?(r="\\",n++):(r=k,0===v&&f(X)));v--;r===k?p=void 0:(n=p,p=k);p!==k?(a.length>n?(r=a.charAt(n),n++):(r=k,0===v&&f(pb)),r!==k?l=r:(n=l,l=k)):(n=l,l=k);l===k&&(l=n,92===a.charCodeAt(n)?(p="\\",n++):(p=k,0===v&&f(X)),p!==k?(r=qb(),r!==k?l=r:(n=l,l=k)):(n=l,l=k));return l}function F(){var l;var p=l=n;v++;if(39===a.charCodeAt(n)){var r="'";n++}else r=k,0===v&&f(ma);r===k&&(92===a.charCodeAt(n)?(r="\\",n++):(r=k,0===v&&f(X)));v--;r===k?p=void 0:(n=p,p=k);p!==k?(a.length>n?(r=a.charAt(n),
n++):(r=k,0===v&&f(pb)),r!==k?l=r:(n=l,l=k)):(n=l,l=k);l===k&&(l=n,92===a.charCodeAt(n)?(p="\\",n++):(p=k,0===v&&f(X)),p!==k?(r=qb(),r!==k?l=r:(n=l,l=k)):(n=l,l=k));return l}function qb(){if(39===a.charCodeAt(n)){var l="'";n++}else l=k,0===v&&f(ma);l===k&&(34===a.charCodeAt(n)?(l='"',n++):(l=k,0===v&&f(la)),l===k&&(92===a.charCodeAt(n)?(l="\\",n++):(l=k,0===v&&f(X))));return l}function H(){v++;var l=[];if(rb.test(a.charAt(n))){var p=a.charAt(n);n++}else p=k,0===v&&f(sb);for(;p!==k;)l.push(p),rb.test(a.charAt(n))?
(p=a.charAt(n),n++):(p=k,0===v&&f(sb));v--;l===k&&0===v&&f(kc);return l}var D=void 0!==D?D:{};var k={},tb={ha:g},ub=g,gc=b("outer",!1),hc=b("{",!1),ic=b("}",!1),jc=b(":",!1),nb=/^[a-z]/,ob=c([["a","z"]],!1,!1),lb=/^[a-z0-9_]/,mb=c([["a","z"],["0","9"],"_"],!1,!1),la=b('"',!1),ma=b("'",!1),X=b("\\",!1),pb={type:"any"},kc={type:"other",description:"space"},rb=/^[ \t]/,sb=c([" ","\t"],!1,!1),n=0,ka=[{line:1,H:1}],C=0,ya=[],v=0;if(void 0!==D.U){if(!(D.U in tb))throw Error("Can't start parsing from rule \""+
D.U+'".');ub=tb[D.U]}D=ub();if(D!==k&&n===a.length)return D;D!==k&&n<a.length&&f({type:"end"});throw function(l,p,r){return new Ub(Vb(l,p),l,p,r)}(ya,C<a.length?a.charAt(C):null,C<a.length?e(C,C+1):e(C,C));};function Xb(a){var b;try{var c=Wb(a)}catch(d){if(d instanceof N)throw d;throw new N('Failed to parse semantic locator "'+a+'". '+(null!==(b=d.message)&&void 0!==b?b:d));}if(Va()&&!(c instanceof V))throw Error("parse("+a+") didn't return a SemanticLocator. Return value "+JSON.stringify(c));a=c;if(0===a.R.length&&0===a.L.length)throw new N("Locator is empty");return a};function Yb(a,b,c){var d=W(a,b,!0);d=T(d)?[]:d.o;b=W(a,b,!1,!0);b=T(b)?[]:b.o;a="Didn't find any elements matching semantic locator "+a+". ";var e=c.u,f=c.D,g=c.C;c=c.A;var h=1<e.length;0===c.length?void 0===f?a+="No elements have "+U(g)+".":(a+=e.length+" element"+(h?"s":"")+" with "+(Ob(f)+" were found. "),a+="However "+(h?"none had":"it didn't have")+" "+(U(g)+". ")+(Pb(g,e)+".")):void 0===f?a+=e.length+" element"+(h?"s":"")+" matched the locator "+(c.join(" ")+", but ")+((h?"none had":"it didn't have")+
" a descendant with ")+(U(g)+"."):(a+=e.length+" descendant"+(h?"s":"")+" of "+(c.join(" ")+" with "+Ob(f)+" were found. "),a+="However "+(h?"none had":"it didn't have")+" "+(U(g)+". ")+(Pb(g,e)+"."));0<d.length&&(a+=" "+d.length+" hidden element"+((1<d.length?"s":"")+" matched the locator. To match these elements, ensure they're not hidden (aria-hidden is false and they're not hidden by css)."));0<b.length&&(d=1<b.length,a+=" "+b.length+" element"+((d?"s":"")+" would have matched the locator, but ")+
((d?"have":"it has")+" an ancestor with presentational children (https://www.w3.org/TR/wai-aria-practices/#children_presentational), erasing its semantics."));return a}function W(a,b,c,d){b=void 0===b?document.body:b;c=void 0===c?!1:c;d=void 0===d?!1:d;var e=null;L?e=Zb(a,b,c,d):Za(function(){e=Zb(a,b,c,d)});return e}var Zb=$a($b);
function $b(a,b,c,d){b=ac(a.R,[b],c,d);if(T(b)||0===a.L.length)return b;b=b.o.map(function(f){return ac(a.L,[f],c,d)});var e=b.filter(Nb).flatMap(function(f){return Sb(f.o)});return 0===e.length?(b=Qb(b),{A:a.R.concat(b.A),u:b.u,C:b.C,D:b.D}):{o:Wa(e.sort(I))}}function ac(a,b,c,d){for(var e=0;e<a.length;e++){b=bc(a[e],b,c,d);if(T(b))return{A:a.slice(0,e),u:b.u,C:b.C,D:b.D};b=b.o}return{o:b}}
function bc(a,b,c,d){b=Sb(b);var e=b.flatMap(function(h){return Bb(a.i,h,c,d)});if(0===e.length)return{A:[],u:b,C:{i:a.i}};var f=a.attributes;for(b={G:0};b.G<f.length;b={G:b.G},b.G++){var g=e.filter(function(h){return function(m){return Mb(m,f[h.G].name)===f[h.G].value}}(b));if(0===g.length)return{A:[],u:e,C:{s:f[b.G]},D:{i:a.i,attributes:f.slice(0,b.G)}};e=g}if(a.name){b=e.filter(function(h){a:{var m=a.name;h=db(h);if("*"===m)throw new cb("* is invalid as an accessible name. To match any accessible name omit it from the locator e.g. {button}.");
var q=m.split("*");if(h.startsWith(q[0])&&h.endsWith(q[q.length-1])){m=0;q=y(q);for(var u=q.next();!u.done;u=q.next()){u=u.value;m=h.indexOf(u,m);if(-1===m){h=!1;break a}m+=u.length}h=!0}else h=!1}return h});if(0===b.length)return{A:[],u:e,C:{name:a.name},D:{i:a.i,attributes:a.attributes}};e=b}Ua(e);return{o:e}};function cc(a,b){if(b&&!b.contains(a))throw Error("Can't generate locator for element that is not contained within the root element.");if(!b){a=a.ownerDocument;if(!a)throw Error("Can't generate locator for detached element");b=a.body}return b}
function dc(a,b){var c,d=a.parentElement?R(a.parentElement,Db):null;if(null!==d)return console.warn("Element "+d+" has a role of "+(S(d)+", so it has presentational children (https://www.w3.org/TR/wai-aria-practices/#children_presentational). These presentational elements will be ignored while generating this semantic locator")),dc(d,b);a=ec(a,b);if(null===a)return null;d=[a.node];for(var e=a.element.parentElement,f=Y(d,b);null!==e&&!f.every(function(m){return e.contains(m)});){var g=ec(e,b);if(null!==
g){var h=[].concat(z(d));h.unshift(g.node);h=Y(h,b);h.length<f.length&&d.unshift(g.node);f=h}e=null!==(c=null===g||void 0===g?void 0:g.element.parentElement)&&void 0!==c?c:null}K(f.includes(a.element),"Cannot find element again with locator we just generated:\nNodes: "+(d+"\nElement: ")+(a.element.outerHTML+"\n"));return{Y:d,element:a.element}}
function fc(a,b,c){K(0!==a.length,"Trying to refine empty array of nodes");if(2>=a.length)var d=a;else{d=Y(a,c);for(var e=a.slice(0,1),f=1;f<a.length-1;f++){var g=e.concat(a.slice(f+1));Y(g,c).length>d.length&&e.push(a[f])}e.push(a[a.length-1]);d=e}e=d;K(Y(e,c).includes(b),"Removing redundant nodes does not resolve element anymore:\nInitial nodes: "+(a+"\nAfter refinement: ")+(e+"\n"));a=new V(e,[]);d=lc(a,c);e=new V([],e);c=lc(e,c);return c.includes(b)&&c.length<d.length?e:a}
function ec(a,b){for(;null!==a&&b.contains(a)&&b!==a;){var c=mc(a);if(null!==c)return{node:c,element:a};a=a.parentElement}return null}function mc(a){if(Cb(a))return null;var b=S(a);return null===b?null:new Tb(b,[],db(a))}function lc(a,b){var c=W(a,b);Xa(Nb(c),function(){return"assuredFindByLocator found no elements: "+Yb(a,b,c)+";"});return c.o}function Y(a,b){a=new V(a,[]);return lc(a,b)};function nc(a){return function(){var b=pa.apply(0,arguments);try{return a.apply(null,z(b))}catch(c){throw c instanceof M&&(c=Error(c.P+": "+c.message)),c;}}}function Z(a,b){"function"===typeof b&&(b=nc(b));window[a]=b}Z("findElementsBySemanticLocator",function(a,b){b=void 0===b?document.body:b;a=W(Xb(a),b);return T(a)?[]:a.o});Z("findElementBySemanticLocator",function(a,b){b=void 0===b?document.body:b;a=Xb(a);var c=W(a,b);if(T(c))throw new bb(Yb(a,b,c));return c.o[0]});
Z("closestPreciseLocatorFor",function(a,b){b=cc(a,b);if(!b)return null;a=dc(a,b);return null===a?null:fc(a.Y,a.element,b).toString()});Z("preciseLocatorFor",function(a,b){b=cc(a,b);if(!b)return null;var c=dc(a,b);return null===c||c.element!==a?null:fc(c.Y,c.element,b).toString()});Z("closestSimpleLocatorFor",function(a,b){var c,d,e;return(b=cc(a,b))?null!==(e=null===(d=null===(c=ec(a,b))||void 0===c?void 0:c.node)||void 0===d?void 0:d.toString())&&void 0!==e?e:null:null});
Z("simpleLocatorFor",function(a){var b,c;return null!==(c=null===(b=mc(a))||void 0===b?void 0:b.toString())&&void 0!==c?c:null});Z("semanticLocatorsReady",!0);}).call(this);
