name: Lint javascript
on:
  push:
    branches:
    - main
    paths:
    - 'javascript/**'
  pull_request:
    branches:
    - main
    paths:
    - 'javascript/**'

jobs:
  lint_javascript:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Lint javascript
        working-directory: ./javascript
        run: |
          yarn install --frozen-lockfile
          yarn check-lint
          yarn check-format
