name: Lint webdriver_python
on:
  push:
    branches:
    - main
    paths:
    - 'webdriver_python/**'
  pull_request:
    branches:
    - main
    paths:
    - 'webdriver_python/**'

permissions:
  contents: read

jobs:
  lint_webdriver_python:
    permissions:
      actions: write  # for styfle/cancel-workflow-action to cancel/stop running workflows
      contents: read  # for actions/checkout to fetch code
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bdb12b622a910dfdc99a31fdfe6f45a16bc287a4 # v1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Cancel previous
        uses: styfle/cancel-workflow-action@3d86a7cc43670094ac248017207be0295edbc31d # 0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5 # v2
      - uses: actions/setup-python@7f80679172b057fc5e90d70d197929d454754a5a # v2
        with:
          python-version: 3.6
      - uses: abatilo/actions-poetry@1f9adef0261964471fcf93ba269e1762a33a8a26 # v2.0.0

      - name: Lint webdriver_python
        run: |
          cd webdriver_python
          poetry install
          ./scripts/lint.sh
