name: Test javascript
on:
  push:
    branches:
    - main
    paths:
    - 'javascript/**'
  pull_request:
    branches:
    - main
    paths:
    - 'javascript/**'

permissions:
  contents: read

jobs:
  test_javascript:
    permissions:
      actions: write  # for styfle/cancel-workflow-action to cancel/stop running workflows
      contents: read  # for actions/checkout to fetch code
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bdb12b622a910dfdc99a31fdfe6f45a16bc287a4 # v1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Cancel previous
        uses: styfle/cancel-workflow-action@3d86a7cc43670094ac248017207be0295edbc31d # 0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5 # v2
      - name: Setup node
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # v2
        with:
          node-version: '14'

      - name: Test javascript
        working-directory: ./javascript
        run: |
          yarn install --frozen-lockfile
          yarn test
