name: Test webdriver_java
on:
  push:
    branches:
    - main
    paths:
    - 'javascript/**'
    - 'webdriver_java/**'
  pull_request:
    branches:
    - main
    paths:
    - 'javascript/**'
    - 'webdriver_java/**'

permissions:
  contents: read

jobs:
  test_webdriver_java:
    permissions:
      actions: write  # for styfle/cancel-workflow-action to cancel/stop running workflows
      contents: read  # for actions/checkout to fetch code
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bdb12b622a910dfdc99a31fdfe6f45a16bc287a4 # v1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Cancel previous
        uses: styfle/cancel-workflow-action@3d86a7cc43670094ac248017207be0295edbc31d # 0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5 # v2
      - name: Setup JDK 1.8
        uses: actions/setup-java@e54a62b3df9364d4b4c1c29c7225e57fe605d7dd # v1
        with:
          java-version: 1.8

      - name: Test webdriver_java
        run: |
          cd webdriver_java
          mvn test
